// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type HealthResponse struct {
	Status string `json:"status"`
}

type TicketRequest struct {
	DeviceId  string `json:"device_id,optional"`
	SessionId string `json:"session_id,optional"`
}

type TicketResponse struct {
	Ticket    string `json:"ticket"`
	ExpiresIn int64  `json:"expires_in"`
	SessionId string `json:"session_id"`
	DeviceId  string `json:"device_id"`
}
