// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AckMessagesRequest struct {
	ConversationId string  `json:"conversation_id"`
	AckType        string  `json:"ack_type"`
	Seqs           []int64 `json:"seqs"`
}

type AckMessagesResponse struct {
	Accepted  bool   `json:"accepted"`
	ErrorCode string `json:"error_code,optional"`
	Message   string `json:"message"`
	Updated   int32  `json:"updated"`
}

type AddConversationMembersRequest struct {
	ConversationId string        `path:"conversation_id"`
	Members        []MemberInput `json:"members"`
}

type AuthTokenResponse struct {
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"-"`
	ExpiresIn    int64        `json:"expires_in"`
	TokenType    string       `json:"token_type"`
	User         AuthUserInfo `json:"user"`
}

type AuthUserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email,optional"`
	Avatar   string `json:"avatar,optional"`
}

type Conversation struct {
	ConversationId string `json:"conversation_id"`
	Type           string `json:"type"`
	Status         string `json:"status"`
	Title          string `json:"title"`
	OwnerUserId    string `json:"owner_user_id"`
	CurrentSeq     int64  `json:"current_seq"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type ConversationActionRequest struct {
	ConversationId string `path:"conversation_id"`
}

type ConversationCursor struct {
	ConversationId string `json:"conversation_id"`
	LastSeq        int64  `json:"last_seq"`
}

type ConversationListItem struct {
	Conversation Conversation         `json:"conversation"`
	Member       ConversationMember   `json:"member"`
	Settings     ConversationSettings `json:"settings"`
	MemberCount  int32                `json:"member_count"`
	LastMessage  MessageItem          `json:"last_message,optional"`
	LatestSeq    int64                `json:"latest_seq"`
	UnreadCount  int64                `json:"unread_count"`
}

type ConversationMember struct {
	ConversationId   string `json:"conversation_id"`
	UserId           string `json:"user_id"`
	Role             string `json:"role"`
	Status           string `json:"status"`
	MutedUntil       string `json:"muted_until,optional"`
	JoinedAt         string `json:"joined_at"`
	UpdatedAt        string `json:"updated_at"`
	VisibleFromSeq   int64  `json:"visible_from_seq"`
	VisibleToSeq     int64  `json:"visible_to_seq"`
	LastReadSeq      int64  `json:"last_read_seq"`
	LastDeliveredSeq int64  `json:"last_delivered_seq"`
	LastReadAt       string `json:"last_read_at,optional"`
}

type ConversationResponse struct {
	Accepted     bool                 `json:"accepted"`
	ErrorCode    string               `json:"error_code,optional"`
	Message      string               `json:"message"`
	Conversation Conversation         `json:"conversation"`
	Members      []ConversationMember `json:"members,optional"`
	Settings     ConversationSettings `json:"settings,optional"`
}

type ConversationSettings struct {
	ConversationId string `json:"conversation_id"`
	UserId         string `json:"user_id"`
	Pinned         bool   `json:"pinned"`
	MutedUntil     string `json:"muted_until,optional"`
	Remark         string `json:"remark,optional"`
	UpdatedAt      string `json:"updated_at"`
}

type ConversationSyncResult struct {
	ConversationId string        `json:"conversation_id"`
	Messages       []MessageItem `json:"messages"`
	LatestSeq      int64         `json:"latest_seq"`
}

type CreateDirectConversationRequest struct {
	PeerUserId string `json:"peer_user_id"`
	Title      string `json:"title,optional"`
}

type CreateGroupConversationRequest struct {
	Title   string        `json:"title"`
	Members []MemberInput `json:"members"`
}

type EmptyResponse struct {
	Success   bool   `json:"success"`
	ErrorCode string `json:"error_code,optional"`
	Message   string `json:"message,optional"`
}

type GetConversationRequest struct {
	ConversationId string `path:"conversation_id"`
}

type HealthResponse struct {
	Status string `json:"status"`
}

type ListConversationsRequest struct {
	Limit  int32 `form:"limit,optional"`
	Offset int32 `form:"offset,optional"`
}

type ListConversationsResponse struct {
	Items []ConversationListItem `json:"items"`
}

type ListMessagesRequest struct {
	ConversationId string `path:"conversation_id"`
	AfterSeq       int64  `form:"after_seq,optional"`
	BeforeSeq      int64  `form:"before_seq,optional"`
	Direction      string `form:"direction,optional"`
	Limit          int32  `form:"limit,optional"`
}

type ListMessagesResponse struct {
	Accepted  bool          `json:"accepted"`
	ErrorCode string        `json:"error_code,optional"`
	Message   string        `json:"message"`
	Messages  []MessageItem `json:"messages"`
	LatestSeq int64         `json:"latest_seq"`
}

type LoginRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LogoutRequest struct {
	RefreshToken string `json:"-"`
}

type MemberInput struct {
	UserId string `json:"user_id"`
	Role   string `json:"role,optional"`
}

type MessageItem struct {
	MessageId      string `json:"message_id"`
	ConversationId string `json:"conversation_id"`
	Seq            int64  `json:"seq"`
	SenderId       string `json:"sender_id"`
	DeviceId       string `json:"device_id"`
	ClientMsgId    string `json:"client_msg_id"`
	ClientSeq      int64  `json:"client_seq"`
	ContentType    string `json:"content_type"`
	ContentJson    string `json:"content_json"`
	CreatedAt      string `json:"created_at"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"-"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Password string `json:"password"`
}

type RemoveConversationMemberRequest struct {
	ConversationId string `path:"conversation_id"`
	UserId         string `path:"user_id"`
}

type SyncMessagesRequest struct {
	Cursors              []ConversationCursor `json:"cursors"`
	LimitPerConversation int32                `json:"limit_per_conversation,optional"`
}

type SyncMessagesResponse struct {
	Accepted      bool                     `json:"accepted"`
	ErrorCode     string                   `json:"error_code,optional"`
	Message       string                   `json:"message"`
	Conversations []ConversationSyncResult `json:"conversations"`
}

type TicketRequest struct {
	DeviceId  string `json:"device_id,optional"`
	SessionId string `json:"session_id,optional"`
}

type TicketResponse struct {
	Ticket    string `json:"ticket"`
	ExpiresIn int64  `json:"expires_in"`
	SessionId string `json:"session_id"`
	DeviceId  string `json:"device_id"`
}

type TransferOwnerRequest struct {
	ConversationId string `path:"conversation_id"`
	TargetUserId   string `json:"target_user_id"`
}

type UpdateConversationSettingsRequest struct {
	ConversationId string `path:"conversation_id"`
	Pinned         bool   `json:"pinned"`
	MutedUntil     string `json:"muted_until,optional"`
	Remark         string `json:"remark,optional"`
}

type UpdateMemberRoleRequest struct {
	ConversationId string `path:"conversation_id"`
	UserId         string `path:"user_id"`
	Role           string `json:"role"`
}
