// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/HappyLadySauce/Beehive-IM/services/edge/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: healthzHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/conversations/:conversation_id/messages",
				Handler: listMessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/messages/ack",
				Handler: ackMessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/messages/sync",
				Handler: syncMessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/ws/ticket",
				Handler: createWsTicketHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: websocketHandler(serverCtx),
			},
		},
	)
}
