// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/user/internal/logic"
	"github.com/HappyLadySauce/Beehive-IM/services/user/internal/svc"
	"github.com/HappyLadySauce/Beehive-IM/services/user/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) GetUser(ctx context.Context, in *pb.GetUserRequest) (*pb.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
