// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId           string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	EdgeId           string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	UserId           string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId         string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Jti              string                 `protobuf:"bytes,6,opt,name=jti,proto3" json:"jti,omitempty"`
	LastClientSeq    int64                  `protobuf:"varint,7,opt,name=last_client_seq,json=lastClientSeq,proto3" json:"last_client_seq,omitempty"`
	LastDeliveredSeq int64                  `protobuf:"varint,8,opt,name=last_delivered_seq,json=lastDeliveredSeq,proto3" json:"last_delivered_seq,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *AttachRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *AttachRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *AttachRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AttachRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AttachRequest) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *AttachRequest) GetLastClientSeq() int64 {
	if x != nil {
		return x.LastClientSeq
	}
	return 0
}

func (x *AttachRequest) GetLastDeliveredSeq() int64 {
	if x != nil {
		return x.LastDeliveredSeq
	}
	return 0
}

type AttachResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	GatewayId     string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *AttachResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AttachResponse) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *AttachResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AttachResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResumeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId           string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	EdgeId           string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	UserId           string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId         string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastClientSeq    int64                  `protobuf:"varint,6,opt,name=last_client_seq,json=lastClientSeq,proto3" json:"last_client_seq,omitempty"`
	LastDeliveredSeq int64                  `protobuf:"varint,7,opt,name=last_delivered_seq,json=lastDeliveredSeq,proto3" json:"last_delivered_seq,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResumeRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *ResumeRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *ResumeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResumeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ResumeRequest) GetLastClientSeq() int64 {
	if x != nil {
		return x.LastClientSeq
	}
	return 0
}

func (x *ResumeRequest) GetLastDeliveredSeq() int64 {
	if x != nil {
		return x.LastDeliveredSeq
	}
	return 0
}

type ResumeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Accepted         bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	GatewayId        string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	LastDeliveredSeq int64                  `protobuf:"varint,3,opt,name=last_delivered_seq,json=lastDeliveredSeq,proto3" json:"last_delivered_seq,omitempty"`
	ErrorCode        string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message          string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ResumeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ResumeResponse) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ResumeResponse) GetLastDeliveredSeq() int64 {
	if x != nil {
		return x.LastDeliveredSeq
	}
	return 0
}

func (x *ResumeResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ResumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CloseSessionRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *CloseSessionRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *CloseSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Closed        bool                   `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *CloseSessionResponse) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type GatewayFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	FrameType     string                 `protobuf:"bytes,3,opt,name=frame_type,json=frameType,proto3" json:"frame_type,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	ClientSeq     int64                  `protobuf:"varint,5,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
	ServerSeq     int64                  `protobuf:"varint,6,opt,name=server_seq,json=serverSeq,proto3" json:"server_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayFrame) Reset() {
	*x = GatewayFrame{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayFrame) ProtoMessage() {}

func (x *GatewayFrame) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayFrame.ProtoReflect.Descriptor instead.
func (*GatewayFrame) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GatewayFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GatewayFrame) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *GatewayFrame) GetFrameType() string {
	if x != nil {
		return x.FrameType
	}
	return ""
}

func (x *GatewayFrame) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *GatewayFrame) GetClientSeq() int64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *GatewayFrame) GetServerSeq() int64 {
	if x != nil {
		return x.ServerSeq
	}
	return 0
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\x12beehive_im.gateway\"\xfe\x01\n" +
	"\rAttachRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x10\n" +
	"\x03jti\x18\x06 \x01(\tR\x03jti\x12&\n" +
	"\x0flast_client_seq\x18\a \x01(\x03R\rlastClientSeq\x12,\n" +
	"\x12last_delivered_seq\x18\b \x01(\x03R\x10lastDeliveredSeq\"\x84\x01\n" +
	"\x0eAttachResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xec\x01\n" +
	"\rResumeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12&\n" +
	"\x0flast_client_seq\x18\x06 \x01(\x03R\rlastClientSeq\x12,\n" +
	"\x12last_delivered_seq\x18\a \x01(\x03R\x10lastDeliveredSeq\"\xb2\x01\n" +
	"\x0eResumeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\x12,\n" +
	"\x12last_delivered_seq\x18\x03 \x01(\x03R\x10lastDeliveredSeq\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"~\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\".\n" +
	"\x14CloseSessionResponse\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\bR\x06closed\"\xc6\x01\n" +
	"\fGatewayFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x1d\n" +
	"\n" +
	"frame_type\x18\x03 \x01(\tR\tframeType\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x05 \x01(\x03R\tclientSeq\x12\x1d\n" +
	"\n" +
	"server_seq\x18\x06 \x01(\x03R\tserverSeq2\xe7\x02\n" +
	"\x0eGatewayService\x12O\n" +
	"\x06Attach\x12!.beehive_im.gateway.AttachRequest\x1a\".beehive_im.gateway.AttachResponse\x12O\n" +
	"\x06Resume\x12!.beehive_im.gateway.ResumeRequest\x1a\".beehive_im.gateway.ResumeResponse\x12a\n" +
	"\fCloseSession\x12'.beehive_im.gateway.CloseSessionRequest\x1a(.beehive_im.gateway.CloseSessionResponse\x12P\n" +
	"\x06Stream\x12 .beehive_im.gateway.GatewayFrame\x1a .beehive_im.gateway.GatewayFrame(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gateway_proto_goTypes = []any{
	(*AttachRequest)(nil),        // 0: beehive_im.gateway.AttachRequest
	(*AttachResponse)(nil),       // 1: beehive_im.gateway.AttachResponse
	(*ResumeRequest)(nil),        // 2: beehive_im.gateway.ResumeRequest
	(*ResumeResponse)(nil),       // 3: beehive_im.gateway.ResumeResponse
	(*CloseSessionRequest)(nil),  // 4: beehive_im.gateway.CloseSessionRequest
	(*CloseSessionResponse)(nil), // 5: beehive_im.gateway.CloseSessionResponse
	(*GatewayFrame)(nil),         // 6: beehive_im.gateway.GatewayFrame
}
var file_gateway_proto_depIdxs = []int32{
	0, // 0: beehive_im.gateway.GatewayService.Attach:input_type -> beehive_im.gateway.AttachRequest
	2, // 1: beehive_im.gateway.GatewayService.Resume:input_type -> beehive_im.gateway.ResumeRequest
	4, // 2: beehive_im.gateway.GatewayService.CloseSession:input_type -> beehive_im.gateway.CloseSessionRequest
	6, // 3: beehive_im.gateway.GatewayService.Stream:input_type -> beehive_im.gateway.GatewayFrame
	1, // 4: beehive_im.gateway.GatewayService.Attach:output_type -> beehive_im.gateway.AttachResponse
	3, // 5: beehive_im.gateway.GatewayService.Resume:output_type -> beehive_im.gateway.ResumeResponse
	5, // 6: beehive_im.gateway.GatewayService.CloseSession:output_type -> beehive_im.gateway.CloseSessionResponse
	6, // 7: beehive_im.gateway.GatewayService.Stream:output_type -> beehive_im.gateway.GatewayFrame
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
