// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: conversation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conversation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	OwnerUserId    string                 `protobuf:"bytes,5,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	CurrentSeq     int64                  `protobuf:"varint,6,opt,name=current_seq,json=currentSeq,proto3" json:"current_seq,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Conversation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Conversation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Conversation) GetCurrentSeq() int64 {
	if x != nil {
		return x.CurrentSeq
	}
	return 0
}

func (x *Conversation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Conversation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ConversationMember struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	MutedUntil     string                 `protobuf:"bytes,5,opt,name=muted_until,json=mutedUntil,proto3" json:"muted_until,omitempty"`
	JoinedAt       string                 `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationMember) Reset() {
	*x = ConversationMember{}
	mi := &file_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMember) ProtoMessage() {}

func (x *ConversationMember) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMember.ProtoReflect.Descriptor instead.
func (*ConversationMember) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *ConversationMember) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConversationMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationMember) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConversationMember) GetMutedUntil() string {
	if x != nil {
		return x.MutedUntil
	}
	return ""
}

func (x *ConversationMember) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *ConversationMember) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ConversationSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pinned         bool                   `protobuf:"varint,3,opt,name=pinned,proto3" json:"pinned,omitempty"`
	MutedUntil     string                 `protobuf:"bytes,4,opt,name=muted_until,json=mutedUntil,proto3" json:"muted_until,omitempty"`
	Remark         string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationSettings) Reset() {
	*x = ConversationSettings{}
	mi := &file_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSettings) ProtoMessage() {}

func (x *ConversationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSettings.ProtoReflect.Descriptor instead.
func (*ConversationSettings) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *ConversationSettings) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationSettings) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConversationSettings) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *ConversationSettings) GetMutedUntil() string {
	if x != nil {
		return x.MutedUntil
	}
	return ""
}

func (x *ConversationSettings) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ConversationSettings) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MemberInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInput) Reset() {
	*x = MemberInput{}
	mi := &file_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInput) ProtoMessage() {}

func (x *MemberInput) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInput.ProtoReflect.Descriptor instead.
func (*MemberInput) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *MemberInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MemberInput) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorUserId string                 `protobuf:"bytes,1,opt,name=creator_user_id,json=creatorUserId,proto3" json:"creator_user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Members       []*MemberInput         `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *CreateConversationRequest) GetCreatorUserId() string {
	if x != nil {
		return x.CreatorUserId
	}
	return ""
}

func (x *CreateConversationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateConversationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateConversationRequest) GetMembers() []*MemberInput {
	if x != nil {
		return x.Members
	}
	return nil
}

type CreateConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Conversation  *Conversation          `protobuf:"bytes,4,opt,name=conversation,proto3" json:"conversation,omitempty"`
	Members       []*ConversationMember  `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationResponse) Reset() {
	*x = CreateConversationResponse{}
	mi := &file_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResponse) ProtoMessage() {}

func (x *CreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResponse.ProtoReflect.Descriptor instead.
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *CreateConversationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CreateConversationResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CreateConversationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateConversationResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *CreateConversationResponse) GetMembers() []*ConversationMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type GetConversationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RequesterUserId string                 `protobuf:"bytes,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *GetConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetConversationRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

type GetConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Conversation  *Conversation          `protobuf:"bytes,4,opt,name=conversation,proto3" json:"conversation,omitempty"`
	Members       []*ConversationMember  `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	Settings      *ConversationSettings  `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationResponse) Reset() {
	*x = GetConversationResponse{}
	mi := &file_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationResponse) ProtoMessage() {}

func (x *GetConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationResponse.ProtoReflect.Descriptor instead.
func (*GetConversationResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *GetConversationResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetConversationResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetConversationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetConversationResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *GetConversationResponse) GetMembers() []*ConversationMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetConversationResponse) GetSettings() *ConversationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *ListConversationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConversationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type AddMembersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ActorUserId    string                 `protobuf:"bytes,2,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	Members        []*MemberInput         `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddMembersRequest) Reset() {
	*x = AddMembersRequest{}
	mi := &file_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersRequest) ProtoMessage() {}

func (x *AddMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersRequest.ProtoReflect.Descriptor instead.
func (*AddMembersRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *AddMembersRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AddMembersRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *AddMembersRequest) GetMembers() []*MemberInput {
	if x != nil {
		return x.Members
	}
	return nil
}

type AddMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Members       []*ConversationMember  `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMembersResponse) Reset() {
	*x = AddMembersResponse{}
	mi := &file_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersResponse) ProtoMessage() {}

func (x *AddMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersResponse.ProtoReflect.Descriptor instead.
func (*AddMembersResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *AddMembersResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AddMembersResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AddMembersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddMembersResponse) GetMembers() []*ConversationMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type RemoveMembersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ActorUserId    string                 `protobuf:"bytes,2,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	UserIds        []string               `protobuf:"bytes,3,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveMembersRequest) Reset() {
	*x = RemoveMembersRequest{}
	mi := &file_conversation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMembersRequest) ProtoMessage() {}

func (x *RemoveMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMembersRequest.ProtoReflect.Descriptor instead.
func (*RemoveMembersRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveMembersRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RemoveMembersRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *RemoveMembersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type RemoveMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Removed       int32                  `protobuf:"varint,4,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMembersResponse) Reset() {
	*x = RemoveMembersResponse{}
	mi := &file_conversation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMembersResponse) ProtoMessage() {}

func (x *RemoveMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMembersResponse.ProtoReflect.Descriptor instead.
func (*RemoveMembersResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveMembersResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RemoveMembersResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RemoveMembersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveMembersResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type UpdateMemberRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ActorUserId    string                 `protobuf:"bytes,2,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	TargetUserId   string                 `protobuf:"bytes,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_conversation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateMemberRoleRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Member        *ConversationMember    `protobuf:"bytes,4,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleResponse) Reset() {
	*x = UpdateMemberRoleResponse{}
	mi := &file_conversation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleResponse) ProtoMessage() {}

func (x *UpdateMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateMemberRoleResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UpdateMemberRoleResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UpdateMemberRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateMemberRoleResponse) GetMember() *ConversationMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type UpdateConversationSettingsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ActorUserId    string                 `protobuf:"bytes,2,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	TargetUserId   string                 `protobuf:"bytes,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	Pinned         bool                   `protobuf:"varint,4,opt,name=pinned,proto3" json:"pinned,omitempty"`
	MutedUntil     string                 `protobuf:"bytes,5,opt,name=muted_until,json=mutedUntil,proto3" json:"muted_until,omitempty"`
	Remark         string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateConversationSettingsRequest) Reset() {
	*x = UpdateConversationSettingsRequest{}
	mi := &file_conversation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationSettingsRequest) ProtoMessage() {}

func (x *UpdateConversationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateConversationSettingsRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateConversationSettingsRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UpdateConversationSettingsRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *UpdateConversationSettingsRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *UpdateConversationSettingsRequest) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *UpdateConversationSettingsRequest) GetMutedUntil() string {
	if x != nil {
		return x.MutedUntil
	}
	return ""
}

func (x *UpdateConversationSettingsRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdateConversationSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Settings      *ConversationSettings  `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationSettingsResponse) Reset() {
	*x = UpdateConversationSettingsResponse{}
	mi := &file_conversation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationSettingsResponse) ProtoMessage() {}

func (x *UpdateConversationSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateConversationSettingsResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateConversationSettingsResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UpdateConversationSettingsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UpdateConversationSettingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateConversationSettingsResponse) GetSettings() *ConversationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CheckSendPermissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckSendPermissionRequest) Reset() {
	*x = CheckSendPermissionRequest{}
	mi := &file_conversation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSendPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSendPermissionRequest) ProtoMessage() {}

func (x *CheckSendPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSendPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckSendPermissionRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{18}
}

func (x *CheckSendPermissionRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CheckSendPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckSendPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSendPermissionResponse) Reset() {
	*x = CheckSendPermissionResponse{}
	mi := &file_conversation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSendPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSendPermissionResponse) ProtoMessage() {}

func (x *CheckSendPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSendPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckSendPermissionResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{19}
}

func (x *CheckSendPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckSendPermissionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CheckSendPermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckReadPermissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckReadPermissionRequest) Reset() {
	*x = CheckReadPermissionRequest{}
	mi := &file_conversation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReadPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReadPermissionRequest) ProtoMessage() {}

func (x *CheckReadPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReadPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckReadPermissionRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{20}
}

func (x *CheckReadPermissionRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CheckReadPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckReadPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReadPermissionResponse) Reset() {
	*x = CheckReadPermissionResponse{}
	mi := &file_conversation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReadPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReadPermissionResponse) ProtoMessage() {}

func (x *CheckReadPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReadPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckReadPermissionResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{21}
}

func (x *CheckReadPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckReadPermissionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CheckReadPermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResolveMessageRecipientsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveMessageRecipientsRequest) Reset() {
	*x = ResolveMessageRecipientsRequest{}
	mi := &file_conversation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMessageRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMessageRecipientsRequest) ProtoMessage() {}

func (x *ResolveMessageRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMessageRecipientsRequest.ProtoReflect.Descriptor instead.
func (*ResolveMessageRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{22}
}

func (x *ResolveMessageRecipientsRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ResolveMessageRecipientsRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type ResolveMessageRecipientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UserIds       []string               `protobuf:"bytes,4,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMessageRecipientsResponse) Reset() {
	*x = ResolveMessageRecipientsResponse{}
	mi := &file_conversation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMessageRecipientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMessageRecipientsResponse) ProtoMessage() {}

func (x *ResolveMessageRecipientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMessageRecipientsResponse.ProtoReflect.Descriptor instead.
func (*ResolveMessageRecipientsResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{23}
}

func (x *ResolveMessageRecipientsResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ResolveMessageRecipientsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ResolveMessageRecipientsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResolveMessageRecipientsResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type AllocateMessageSeqRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AllocateMessageSeqRequest) Reset() {
	*x = AllocateMessageSeqRequest{}
	mi := &file_conversation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateMessageSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateMessageSeqRequest) ProtoMessage() {}

func (x *AllocateMessageSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateMessageSeqRequest.ProtoReflect.Descriptor instead.
func (*AllocateMessageSeqRequest) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{24}
}

func (x *AllocateMessageSeqRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AllocateMessageSeqRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AllocateMessageSeqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Seq           int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateMessageSeqResponse) Reset() {
	*x = AllocateMessageSeqResponse{}
	mi := &file_conversation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateMessageSeqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateMessageSeqResponse) ProtoMessage() {}

func (x *AllocateMessageSeqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateMessageSeqResponse.ProtoReflect.Descriptor instead.
func (*AllocateMessageSeqResponse) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{25}
}

func (x *AllocateMessageSeqResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AllocateMessageSeqResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AllocateMessageSeqResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AllocateMessageSeqResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_conversation_proto protoreflect.FileDescriptor

const file_conversation_proto_rawDesc = "" +
	"\n" +
	"\x12conversation.proto\x12\x17beehive_im.conversation\"\xfc\x01\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\"\n" +
	"\rowner_user_id\x18\x05 \x01(\tR\vownerUserId\x12\x1f\n" +
	"\vcurrent_seq\x18\x06 \x01(\x03R\n" +
	"currentSeq\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xdf\x01\n" +
	"\x12ConversationMember\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vmuted_until\x18\x05 \x01(\tR\n" +
	"mutedUntil\x12\x1b\n" +
	"\tjoined_at\x18\x06 \x01(\tR\bjoinedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xc8\x01\n" +
	"\x14ConversationSettings\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06pinned\x18\x03 \x01(\bR\x06pinned\x12\x1f\n" +
	"\vmuted_until\x18\x04 \x01(\tR\n" +
	"mutedUntil\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\":\n" +
	"\vMemberInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\xad\x01\n" +
	"\x19CreateConversationRequest\x12&\n" +
	"\x0fcreator_user_id\x18\x01 \x01(\tR\rcreatorUserId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12>\n" +
	"\amembers\x18\x04 \x03(\v2$.beehive_im.conversation.MemberInputR\amembers\"\x83\x02\n" +
	"\x1aCreateConversationResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12I\n" +
	"\fconversation\x18\x04 \x01(\v2%.beehive_im.conversation.ConversationR\fconversation\x12E\n" +
	"\amembers\x18\x05 \x03(\v2+.beehive_im.conversation.ConversationMemberR\amembers\"m\n" +
	"\x16GetConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\tR\x0frequesterUserId\"\xc5\x02\n" +
	"\x17GetConversationResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12I\n" +
	"\fconversation\x18\x04 \x01(\v2%.beehive_im.conversation.ConversationR\fconversation\x12E\n" +
	"\amembers\x18\x05 \x03(\v2+.beehive_im.conversation.ConversationMemberR\amembers\x12I\n" +
	"\bsettings\x18\x06 \x01(\v2-.beehive_im.conversation.ConversationSettingsR\bsettings\"a\n" +
	"\x18ListConversationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"h\n" +
	"\x19ListConversationsResponse\x12K\n" +
	"\rconversations\x18\x01 \x03(\v2%.beehive_im.conversation.ConversationR\rconversations\"\xa0\x01\n" +
	"\x11AddMembersRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\ractor_user_id\x18\x02 \x01(\tR\vactorUserId\x12>\n" +
	"\amembers\x18\x03 \x03(\v2$.beehive_im.conversation.MemberInputR\amembers\"\xb0\x01\n" +
	"\x12AddMembersResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12E\n" +
	"\amembers\x18\x04 \x03(\v2+.beehive_im.conversation.ConversationMemberR\amembers\"~\n" +
	"\x14RemoveMembersRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\ractor_user_id\x18\x02 \x01(\tR\vactorUserId\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\tR\auserIds\"\x86\x01\n" +
	"\x15RemoveMembersResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\aremoved\x18\x04 \x01(\x05R\aremoved\"\xa0\x01\n" +
	"\x17UpdateMemberRoleRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\ractor_user_id\x18\x02 \x01(\tR\vactorUserId\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\tR\ftargetUserId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"\xb4\x01\n" +
	"\x18UpdateMemberRoleResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12C\n" +
	"\x06member\x18\x04 \x01(\v2+.beehive_im.conversation.ConversationMemberR\x06member\"\xe7\x01\n" +
	"!UpdateConversationSettingsRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\ractor_user_id\x18\x02 \x01(\tR\vactorUserId\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\tR\ftargetUserId\x12\x16\n" +
	"\x06pinned\x18\x04 \x01(\bR\x06pinned\x12\x1f\n" +
	"\vmuted_until\x18\x05 \x01(\tR\n" +
	"mutedUntil\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\"\xc4\x01\n" +
	"\"UpdateConversationSettingsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12I\n" +
	"\bsettings\x18\x04 \x01(\v2-.beehive_im.conversation.ConversationSettingsR\bsettings\"^\n" +
	"\x1aCheckSendPermissionRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"p\n" +
	"\x1bCheckSendPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"^\n" +
	"\x1aCheckReadPermissionRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"p\n" +
	"\x1bCheckReadPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"g\n" +
	"\x1fResolveMessageRecipientsRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\"\x92\x01\n" +
	" ResolveMessageRecipientsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\buser_ids\x18\x04 \x03(\tR\auserIds\"]\n" +
	"\x19AllocateMessageSeqRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x83\x01\n" +
	"\x1aAllocateMessageSeqResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq2\x85\v\n" +
	"\x13ConversationService\x12}\n" +
	"\x12CreateConversation\x122.beehive_im.conversation.CreateConversationRequest\x1a3.beehive_im.conversation.CreateConversationResponse\x12t\n" +
	"\x0fGetConversation\x12/.beehive_im.conversation.GetConversationRequest\x1a0.beehive_im.conversation.GetConversationResponse\x12z\n" +
	"\x11ListConversations\x121.beehive_im.conversation.ListConversationsRequest\x1a2.beehive_im.conversation.ListConversationsResponse\x12e\n" +
	"\n" +
	"AddMembers\x12*.beehive_im.conversation.AddMembersRequest\x1a+.beehive_im.conversation.AddMembersResponse\x12n\n" +
	"\rRemoveMembers\x12-.beehive_im.conversation.RemoveMembersRequest\x1a..beehive_im.conversation.RemoveMembersResponse\x12w\n" +
	"\x10UpdateMemberRole\x120.beehive_im.conversation.UpdateMemberRoleRequest\x1a1.beehive_im.conversation.UpdateMemberRoleResponse\x12\x95\x01\n" +
	"\x1aUpdateConversationSettings\x12:.beehive_im.conversation.UpdateConversationSettingsRequest\x1a;.beehive_im.conversation.UpdateConversationSettingsResponse\x12\x80\x01\n" +
	"\x13CheckSendPermission\x123.beehive_im.conversation.CheckSendPermissionRequest\x1a4.beehive_im.conversation.CheckSendPermissionResponse\x12\x80\x01\n" +
	"\x13CheckReadPermission\x123.beehive_im.conversation.CheckReadPermissionRequest\x1a4.beehive_im.conversation.CheckReadPermissionResponse\x12\x8f\x01\n" +
	"\x18ResolveMessageRecipients\x128.beehive_im.conversation.ResolveMessageRecipientsRequest\x1a9.beehive_im.conversation.ResolveMessageRecipientsResponse\x12}\n" +
	"\x12AllocateMessageSeq\x122.beehive_im.conversation.AllocateMessageSeqRequest\x1a3.beehive_im.conversation.AllocateMessageSeqResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_conversation_proto_rawDescOnce sync.Once
	file_conversation_proto_rawDescData []byte
)

func file_conversation_proto_rawDescGZIP() []byte {
	file_conversation_proto_rawDescOnce.Do(func() {
		file_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conversation_proto_rawDesc), len(file_conversation_proto_rawDesc)))
	})
	return file_conversation_proto_rawDescData
}

var file_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_conversation_proto_goTypes = []any{
	(*Conversation)(nil),                       // 0: beehive_im.conversation.Conversation
	(*ConversationMember)(nil),                 // 1: beehive_im.conversation.ConversationMember
	(*ConversationSettings)(nil),               // 2: beehive_im.conversation.ConversationSettings
	(*MemberInput)(nil),                        // 3: beehive_im.conversation.MemberInput
	(*CreateConversationRequest)(nil),          // 4: beehive_im.conversation.CreateConversationRequest
	(*CreateConversationResponse)(nil),         // 5: beehive_im.conversation.CreateConversationResponse
	(*GetConversationRequest)(nil),             // 6: beehive_im.conversation.GetConversationRequest
	(*GetConversationResponse)(nil),            // 7: beehive_im.conversation.GetConversationResponse
	(*ListConversationsRequest)(nil),           // 8: beehive_im.conversation.ListConversationsRequest
	(*ListConversationsResponse)(nil),          // 9: beehive_im.conversation.ListConversationsResponse
	(*AddMembersRequest)(nil),                  // 10: beehive_im.conversation.AddMembersRequest
	(*AddMembersResponse)(nil),                 // 11: beehive_im.conversation.AddMembersResponse
	(*RemoveMembersRequest)(nil),               // 12: beehive_im.conversation.RemoveMembersRequest
	(*RemoveMembersResponse)(nil),              // 13: beehive_im.conversation.RemoveMembersResponse
	(*UpdateMemberRoleRequest)(nil),            // 14: beehive_im.conversation.UpdateMemberRoleRequest
	(*UpdateMemberRoleResponse)(nil),           // 15: beehive_im.conversation.UpdateMemberRoleResponse
	(*UpdateConversationSettingsRequest)(nil),  // 16: beehive_im.conversation.UpdateConversationSettingsRequest
	(*UpdateConversationSettingsResponse)(nil), // 17: beehive_im.conversation.UpdateConversationSettingsResponse
	(*CheckSendPermissionRequest)(nil),         // 18: beehive_im.conversation.CheckSendPermissionRequest
	(*CheckSendPermissionResponse)(nil),        // 19: beehive_im.conversation.CheckSendPermissionResponse
	(*CheckReadPermissionRequest)(nil),         // 20: beehive_im.conversation.CheckReadPermissionRequest
	(*CheckReadPermissionResponse)(nil),        // 21: beehive_im.conversation.CheckReadPermissionResponse
	(*ResolveMessageRecipientsRequest)(nil),    // 22: beehive_im.conversation.ResolveMessageRecipientsRequest
	(*ResolveMessageRecipientsResponse)(nil),   // 23: beehive_im.conversation.ResolveMessageRecipientsResponse
	(*AllocateMessageSeqRequest)(nil),          // 24: beehive_im.conversation.AllocateMessageSeqRequest
	(*AllocateMessageSeqResponse)(nil),         // 25: beehive_im.conversation.AllocateMessageSeqResponse
}
var file_conversation_proto_depIdxs = []int32{
	3,  // 0: beehive_im.conversation.CreateConversationRequest.members:type_name -> beehive_im.conversation.MemberInput
	0,  // 1: beehive_im.conversation.CreateConversationResponse.conversation:type_name -> beehive_im.conversation.Conversation
	1,  // 2: beehive_im.conversation.CreateConversationResponse.members:type_name -> beehive_im.conversation.ConversationMember
	0,  // 3: beehive_im.conversation.GetConversationResponse.conversation:type_name -> beehive_im.conversation.Conversation
	1,  // 4: beehive_im.conversation.GetConversationResponse.members:type_name -> beehive_im.conversation.ConversationMember
	2,  // 5: beehive_im.conversation.GetConversationResponse.settings:type_name -> beehive_im.conversation.ConversationSettings
	0,  // 6: beehive_im.conversation.ListConversationsResponse.conversations:type_name -> beehive_im.conversation.Conversation
	3,  // 7: beehive_im.conversation.AddMembersRequest.members:type_name -> beehive_im.conversation.MemberInput
	1,  // 8: beehive_im.conversation.AddMembersResponse.members:type_name -> beehive_im.conversation.ConversationMember
	1,  // 9: beehive_im.conversation.UpdateMemberRoleResponse.member:type_name -> beehive_im.conversation.ConversationMember
	2,  // 10: beehive_im.conversation.UpdateConversationSettingsResponse.settings:type_name -> beehive_im.conversation.ConversationSettings
	4,  // 11: beehive_im.conversation.ConversationService.CreateConversation:input_type -> beehive_im.conversation.CreateConversationRequest
	6,  // 12: beehive_im.conversation.ConversationService.GetConversation:input_type -> beehive_im.conversation.GetConversationRequest
	8,  // 13: beehive_im.conversation.ConversationService.ListConversations:input_type -> beehive_im.conversation.ListConversationsRequest
	10, // 14: beehive_im.conversation.ConversationService.AddMembers:input_type -> beehive_im.conversation.AddMembersRequest
	12, // 15: beehive_im.conversation.ConversationService.RemoveMembers:input_type -> beehive_im.conversation.RemoveMembersRequest
	14, // 16: beehive_im.conversation.ConversationService.UpdateMemberRole:input_type -> beehive_im.conversation.UpdateMemberRoleRequest
	16, // 17: beehive_im.conversation.ConversationService.UpdateConversationSettings:input_type -> beehive_im.conversation.UpdateConversationSettingsRequest
	18, // 18: beehive_im.conversation.ConversationService.CheckSendPermission:input_type -> beehive_im.conversation.CheckSendPermissionRequest
	20, // 19: beehive_im.conversation.ConversationService.CheckReadPermission:input_type -> beehive_im.conversation.CheckReadPermissionRequest
	22, // 20: beehive_im.conversation.ConversationService.ResolveMessageRecipients:input_type -> beehive_im.conversation.ResolveMessageRecipientsRequest
	24, // 21: beehive_im.conversation.ConversationService.AllocateMessageSeq:input_type -> beehive_im.conversation.AllocateMessageSeqRequest
	5,  // 22: beehive_im.conversation.ConversationService.CreateConversation:output_type -> beehive_im.conversation.CreateConversationResponse
	7,  // 23: beehive_im.conversation.ConversationService.GetConversation:output_type -> beehive_im.conversation.GetConversationResponse
	9,  // 24: beehive_im.conversation.ConversationService.ListConversations:output_type -> beehive_im.conversation.ListConversationsResponse
	11, // 25: beehive_im.conversation.ConversationService.AddMembers:output_type -> beehive_im.conversation.AddMembersResponse
	13, // 26: beehive_im.conversation.ConversationService.RemoveMembers:output_type -> beehive_im.conversation.RemoveMembersResponse
	15, // 27: beehive_im.conversation.ConversationService.UpdateMemberRole:output_type -> beehive_im.conversation.UpdateMemberRoleResponse
	17, // 28: beehive_im.conversation.ConversationService.UpdateConversationSettings:output_type -> beehive_im.conversation.UpdateConversationSettingsResponse
	19, // 29: beehive_im.conversation.ConversationService.CheckSendPermission:output_type -> beehive_im.conversation.CheckSendPermissionResponse
	21, // 30: beehive_im.conversation.ConversationService.CheckReadPermission:output_type -> beehive_im.conversation.CheckReadPermissionResponse
	23, // 31: beehive_im.conversation.ConversationService.ResolveMessageRecipients:output_type -> beehive_im.conversation.ResolveMessageRecipientsResponse
	25, // 32: beehive_im.conversation.ConversationService.AllocateMessageSeq:output_type -> beehive_im.conversation.AllocateMessageSeqResponse
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_conversation_proto_init() }
func file_conversation_proto_init() {
	if File_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conversation_proto_rawDesc), len(file_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conversation_proto_goTypes,
		DependencyIndexes: file_conversation_proto_depIdxs,
		MessageInfos:      file_conversation_proto_msgTypes,
	}.Build()
	File_conversation_proto = out.File
	file_conversation_proto_goTypes = nil
	file_conversation_proto_depIdxs = nil
}
