// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: conversation.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/conversation/internal/logic"
	"github.com/HappyLadySauce/Beehive-IM/services/conversation/internal/svc"
	"github.com/HappyLadySauce/Beehive-IM/services/conversation/pb"
)

type ConversationServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedConversationServiceServer
}

func NewConversationServiceServer(svcCtx *svc.ServiceContext) *ConversationServiceServer {
	return &ConversationServiceServer{
		svcCtx: svcCtx,
	}
}

// CreateConversation creates a conversation and initial members.
func (s *ConversationServiceServer) CreateConversation(ctx context.Context, in *pb.CreateConversationRequest) (*pb.CreateConversationResponse, error) {
	l := logic.NewCreateConversationLogic(ctx, s.svcCtx)
	return l.CreateConversation(in)
}

// GetConversation returns one conversation with members and user settings.
func (s *ConversationServiceServer) GetConversation(ctx context.Context, in *pb.GetConversationRequest) (*pb.GetConversationResponse, error) {
	l := logic.NewGetConversationLogic(ctx, s.svcCtx)
	return l.GetConversation(in)
}

// ListConversations returns conversations joined by one user.
func (s *ConversationServiceServer) ListConversations(ctx context.Context, in *pb.ListConversationsRequest) (*pb.ListConversationsResponse, error) {
	l := logic.NewListConversationsLogic(ctx, s.svcCtx)
	return l.ListConversations(in)
}

// AddMembers adds or reactivates members in a conversation.
func (s *ConversationServiceServer) AddMembers(ctx context.Context, in *pb.AddMembersRequest) (*pb.AddMembersResponse, error) {
	l := logic.NewAddMembersLogic(ctx, s.svcCtx)
	return l.AddMembers(in)
}

// RemoveMembers marks members as removed from a conversation.
func (s *ConversationServiceServer) RemoveMembers(ctx context.Context, in *pb.RemoveMembersRequest) (*pb.RemoveMembersResponse, error) {
	l := logic.NewRemoveMembersLogic(ctx, s.svcCtx)
	return l.RemoveMembers(in)
}

// LeaveConversation lets one member leave a group conversation.
func (s *ConversationServiceServer) LeaveConversation(ctx context.Context, in *pb.LeaveConversationRequest) (*pb.LeaveConversationResponse, error) {
	l := logic.NewLeaveConversationLogic(ctx, s.svcCtx)
	return l.LeaveConversation(in)
}

// DismissConversation closes a group conversation by owner.
func (s *ConversationServiceServer) DismissConversation(ctx context.Context, in *pb.DismissConversationRequest) (*pb.DismissConversationResponse, error) {
	l := logic.NewDismissConversationLogic(ctx, s.svcCtx)
	return l.DismissConversation(in)
}

// TransferOwner transfers group ownership to another active member.
func (s *ConversationServiceServer) TransferOwner(ctx context.Context, in *pb.TransferOwnerRequest) (*pb.TransferOwnerResponse, error) {
	l := logic.NewTransferOwnerLogic(ctx, s.svcCtx)
	return l.TransferOwner(in)
}

// UpdateMemberRole changes one member role.
func (s *ConversationServiceServer) UpdateMemberRole(ctx context.Context, in *pb.UpdateMemberRoleRequest) (*pb.UpdateMemberRoleResponse, error) {
	l := logic.NewUpdateMemberRoleLogic(ctx, s.svcCtx)
	return l.UpdateMemberRole(in)
}

// UpdateConversationSettings updates settings owned by one user.
func (s *ConversationServiceServer) UpdateConversationSettings(ctx context.Context, in *pb.UpdateConversationSettingsRequest) (*pb.UpdateConversationSettingsResponse, error) {
	l := logic.NewUpdateConversationSettingsLogic(ctx, s.svcCtx)
	return l.UpdateConversationSettings(in)
}

// MarkConversationRead advances one member read or delivered cursor.
func (s *ConversationServiceServer) MarkConversationRead(ctx context.Context, in *pb.MarkConversationReadRequest) (*pb.MarkConversationReadResponse, error) {
	l := logic.NewMarkConversationReadLogic(ctx, s.svcCtx)
	return l.MarkConversationRead(in)
}

// CheckSendPermission checks whether a user can send to a conversation.
func (s *ConversationServiceServer) CheckSendPermission(ctx context.Context, in *pb.CheckSendPermissionRequest) (*pb.CheckSendPermissionResponse, error) {
	l := logic.NewCheckSendPermissionLogic(ctx, s.svcCtx)
	return l.CheckSendPermission(in)
}

// CheckReadPermission checks whether a user can read a conversation.
func (s *ConversationServiceServer) CheckReadPermission(ctx context.Context, in *pb.CheckReadPermissionRequest) (*pb.CheckReadPermissionResponse, error) {
	l := logic.NewCheckReadPermissionLogic(ctx, s.svcCtx)
	return l.CheckReadPermission(in)
}

// ResolveMessageRecipients returns active users that should receive a message event.
func (s *ConversationServiceServer) ResolveMessageRecipients(ctx context.Context, in *pb.ResolveMessageRecipientsRequest) (*pb.ResolveMessageRecipientsResponse, error) {
	l := logic.NewResolveMessageRecipientsLogic(ctx, s.svcCtx)
	return l.ResolveMessageRecipients(in)
}

// AllocateMessageSeq atomically allocates the next conversation message sequence.
func (s *ConversationServiceServer) AllocateMessageSeq(ctx context.Context, in *pb.AllocateMessageSeqRequest) (*pb.AllocateMessageSeqResponse, error) {
	l := logic.NewAllocateMessageSeqLogic(ctx, s.svcCtx)
	return l.AllocateMessageSeq(in)
}
