// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: auth.proto

package authservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/auth/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GithubCallbackRequest                = pb.GithubCallbackRequest
	LinkGitHubRequest                    = pb.LinkGitHubRequest
	LoginRequest                         = pb.LoginRequest
	LoginResponse                        = pb.LoginResponse
	LogoutRequest                        = pb.LogoutRequest
	LogoutResponse                       = pb.LogoutResponse
	RedirectToGithubAuthorizeUrlRequest  = pb.RedirectToGithubAuthorizeUrlRequest
	RedirectToGithubAuthorizeUrlResponse = pb.RedirectToGithubAuthorizeUrlResponse
	RefreshTokenRequest                  = pb.RefreshTokenRequest
	RegisterRequest                      = pb.RegisterRequest
	RegisterResponse                     = pb.RegisterResponse
	UnlinkGitHubRequest                  = pb.UnlinkGitHubRequest
	UnlinkGitHubResponse                 = pb.UnlinkGitHubResponse
	UserInfo                             = pb.UserInfo

	AuthService interface {
		// --- Local account / 本地账号登录 ---
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
		// Refresh access token using refresh_token
		RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// --- Github OAuth2 authorization code flow / Github 授权登录 ---
		RedirectToGithubAuthorizeUrl(ctx context.Context, in *RedirectToGithubAuthorizeUrlRequest, opts ...grpc.CallOption) (*RedirectToGithubAuthorizeUrlResponse, error)
		// Step2: client sends code from callback; server exchanges token and issues app session
		GithubCallback(ctx context.Context, in *GithubCallbackRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// Step 1 for logged-in user binding GitHub
		LinkGitHub(ctx context.Context, in *LinkGitHubRequest, opts ...grpc.CallOption) (*RedirectToGithubAuthorizeUrlResponse, error)
		// Unbind GitHub from current user
		UnlinkGitHub(ctx context.Context, in *UnlinkGitHubRequest, opts ...grpc.CallOption) (*UnlinkGitHubResponse, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

// --- Local account / 本地账号登录 ---
func (m *defaultAuthService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultAuthService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAuthService) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// Refresh access token using refresh_token
func (m *defaultAuthService) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// --- Github OAuth2 authorization code flow / Github 授权登录 ---
func (m *defaultAuthService) RedirectToGithubAuthorizeUrl(ctx context.Context, in *RedirectToGithubAuthorizeUrlRequest, opts ...grpc.CallOption) (*RedirectToGithubAuthorizeUrlResponse, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.RedirectToGithubAuthorizeUrl(ctx, in, opts...)
}

// Step2: client sends code from callback; server exchanges token and issues app session
func (m *defaultAuthService) GithubCallback(ctx context.Context, in *GithubCallbackRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.GithubCallback(ctx, in, opts...)
}

// Step 1 for logged-in user binding GitHub
func (m *defaultAuthService) LinkGitHub(ctx context.Context, in *LinkGitHubRequest, opts ...grpc.CallOption) (*RedirectToGithubAuthorizeUrlResponse, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.LinkGitHub(ctx, in, opts...)
}

// Unbind GitHub from current user
func (m *defaultAuthService) UnlinkGitHub(ctx context.Context, in *UnlinkGitHubRequest, opts ...grpc.CallOption) (*UnlinkGitHubResponse, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.UnlinkGitHub(ctx, in, opts...)
}
