// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: message.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/message/internal/logic"
	"github.com/HappyLadySauce/Beehive-IM/services/message/internal/svc"
	"github.com/HappyLadySauce/Beehive-IM/services/message/pb"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

// SendMessage validates permissions and persists one client message.
func (s *MessageServiceServer) SendMessage(ctx context.Context, in *pb.SendMessageRequest) (*pb.SendMessageResponse, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

// AckMessages records delivered/read receipts for message sequences.
func (s *MessageServiceServer) AckMessages(ctx context.Context, in *pb.AckMessagesRequest) (*pb.AckMessagesResponse, error) {
	l := logic.NewAckMessagesLogic(ctx, s.svcCtx)
	return l.AckMessages(in)
}
