// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: gateway.proto

package gatewayservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/gateway/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AttachRequest        = pb.AttachRequest
	AttachResponse       = pb.AttachResponse
	CloseSessionRequest  = pb.CloseSessionRequest
	CloseSessionResponse = pb.CloseSessionResponse
	GatewayFrame         = pb.GatewayFrame
	ResumeRequest        = pb.ResumeRequest
	ResumeResponse       = pb.ResumeResponse

	GatewayService interface {
		// Attach creates an upstream session for an Edge connection.
		Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*AttachResponse, error)
		// Resume rebuilds an upstream session after Edge rebind.
		Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
		// CloseSession closes an upstream session owned by Edge.
		CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
		// Stream proxies realtime frames between Edge and Gateway.
		Stream(ctx context.Context, opts ...grpc.CallOption) (pb.GatewayService_StreamClient, error)
	}

	defaultGatewayService struct {
		cli zrpc.Client
	}
)

func NewGatewayService(cli zrpc.Client) GatewayService {
	return &defaultGatewayService{
		cli: cli,
	}
}

// Attach creates an upstream session for an Edge connection.
func (m *defaultGatewayService) Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*AttachResponse, error) {
	client := pb.NewGatewayServiceClient(m.cli.Conn())
	return client.Attach(ctx, in, opts...)
}

// Resume rebuilds an upstream session after Edge rebind.
func (m *defaultGatewayService) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	client := pb.NewGatewayServiceClient(m.cli.Conn())
	return client.Resume(ctx, in, opts...)
}

// CloseSession closes an upstream session owned by Edge.
func (m *defaultGatewayService) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	client := pb.NewGatewayServiceClient(m.cli.Conn())
	return client.CloseSession(ctx, in, opts...)
}

// Stream proxies realtime frames between Edge and Gateway.
func (m *defaultGatewayService) Stream(ctx context.Context, opts ...grpc.CallOption) (pb.GatewayService_StreamClient, error) {
	client := pb.NewGatewayServiceClient(m.cli.Conn())
	return client.Stream(ctx, opts...)
}
