// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: gateway.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/gateway/internal/logic"
	"github.com/HappyLadySauce/Beehive-IM/services/gateway/internal/svc"
	"github.com/HappyLadySauce/Beehive-IM/services/gateway/pb"
)

type GatewayServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGatewayServiceServer
}

func NewGatewayServiceServer(svcCtx *svc.ServiceContext) *GatewayServiceServer {
	return &GatewayServiceServer{
		svcCtx: svcCtx,
	}
}

// Attach creates an upstream session for an Edge connection.
func (s *GatewayServiceServer) Attach(ctx context.Context, in *pb.AttachRequest) (*pb.AttachResponse, error) {
	l := logic.NewAttachLogic(ctx, s.svcCtx)
	return l.Attach(in)
}

// Resume rebuilds an upstream session after Edge rebind.
func (s *GatewayServiceServer) Resume(ctx context.Context, in *pb.ResumeRequest) (*pb.ResumeResponse, error) {
	l := logic.NewResumeLogic(ctx, s.svcCtx)
	return l.Resume(in)
}

// CloseSession closes an upstream session owned by Edge.
func (s *GatewayServiceServer) CloseSession(ctx context.Context, in *pb.CloseSessionRequest) (*pb.CloseSessionResponse, error) {
	l := logic.NewCloseSessionLogic(ctx, s.svcCtx)
	return l.CloseSession(in)
}

// Stream proxies realtime frames between Edge and Gateway.
func (s *GatewayServiceServer) Stream(stream pb.GatewayService_StreamServer) error {
	l := logic.NewStreamLogic(stream.Context(), s.svcCtx)
	return l.Stream(stream)
}
