// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: auth.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/auth/internal/logic"
	"github.com/HappyLadySauce/Beehive-IM/services/auth/internal/svc"
	"github.com/HappyLadySauce/Beehive-IM/services/auth/pb"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

// --- Local account / 本地账号登录 ---
func (s *AuthServiceServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AuthServiceServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthServiceServer) Logout(ctx context.Context, in *pb.LogoutRequest) (*pb.LogoutResponse, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// Refresh access token using refresh_token
func (s *AuthServiceServer) RefreshToken(ctx context.Context, in *pb.RefreshTokenRequest) (*pb.LoginResponse, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

// --- Github OAuth2 authorization code flow / Github 授权登录 ---
func (s *AuthServiceServer) RedirectToGithubAuthorizeUrl(ctx context.Context, in *pb.RedirectToGithubAuthorizeUrlRequest) (*pb.RedirectToGithubAuthorizeUrlResponse, error) {
	l := logic.NewRedirectToGithubAuthorizeUrlLogic(ctx, s.svcCtx)
	return l.RedirectToGithubAuthorizeUrl(in)
}

// Step2: client sends code from callback; server exchanges token and issues app session
func (s *AuthServiceServer) GithubCallback(ctx context.Context, in *pb.GithubCallbackRequest) (*pb.LoginResponse, error) {
	l := logic.NewGithubCallbackLogic(ctx, s.svcCtx)
	return l.GithubCallback(in)
}

// Step 1 for logged-in user binding GitHub
func (s *AuthServiceServer) LinkGitHub(ctx context.Context, in *pb.LinkGitHubRequest) (*pb.RedirectToGithubAuthorizeUrlResponse, error) {
	l := logic.NewLinkGitHubLogic(ctx, s.svcCtx)
	return l.LinkGitHub(in)
}

// Unbind GitHub from current user
func (s *AuthServiceServer) UnlinkGitHub(ctx context.Context, in *pb.UnlinkGitHubRequest) (*pb.UnlinkGitHubResponse, error) {
	l := logic.NewUnlinkGitHubLogic(ctx, s.svcCtx)
	return l.UnlinkGitHub(in)
}
