// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Register_FullMethodName                     = "/beehive_im.auth.AuthService/Register"
	AuthService_Login_FullMethodName                        = "/beehive_im.auth.AuthService/Login"
	AuthService_Logout_FullMethodName                       = "/beehive_im.auth.AuthService/Logout"
	AuthService_RefreshToken_FullMethodName                 = "/beehive_im.auth.AuthService/RefreshToken"
	AuthService_RedirectToGithubAuthorizeUrl_FullMethodName = "/beehive_im.auth.AuthService/RedirectToGithubAuthorizeUrl"
	AuthService_GithubCallback_FullMethodName               = "/beehive_im.auth.AuthService/GithubCallback"
	AuthService_LinkGitHub_FullMethodName                   = "/beehive_im.auth.AuthService/LinkGitHub"
	AuthService_UnlinkGitHub_FullMethodName                 = "/beehive_im.auth.AuthService/UnlinkGitHub"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// --- Local account / 本地账号登录 ---
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// Refresh access token using refresh_token
	// 使用 refresh_token 刷新 access_token
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// --- Github OAuth2 authorization code flow / Github 授权登录 ---
	// Step1: client redirect to Github authorize_url
	// 第一步: 客户端重定向到 Github 授权页面
	RedirectToGithubAuthorizeUrl(ctx context.Context, in *RedirectToGithubAuthorizeUrlRequest, opts ...grpc.CallOption) (*RedirectToGithubAuthorizeUrlResponse, error)
	// Step2: client sends code from callback; server exchanges token and issues app session
	// 第二步: 客户端提交回调 code，服务端换 token 并签发应用会话
	GithubCallback(ctx context.Context, in *GithubCallbackRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Step 1 for logged-in user binding GitHub
	// 已登录用户绑定 GitHub：第一步获取授权 URL
	LinkGitHub(ctx context.Context, in *LinkGitHubRequest, opts ...grpc.CallOption) (*RedirectToGithubAuthorizeUrlResponse, error)
	// Unbind GitHub from current user
	// 解绑当前用户的 GitHub 账号
	UnlinkGitHub(ctx context.Context, in *UnlinkGitHubRequest, opts ...grpc.CallOption) (*UnlinkGitHubResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AuthService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AuthService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RedirectToGithubAuthorizeUrl(ctx context.Context, in *RedirectToGithubAuthorizeUrlRequest, opts ...grpc.CallOption) (*RedirectToGithubAuthorizeUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedirectToGithubAuthorizeUrlResponse)
	err := c.cc.Invoke(ctx, AuthService_RedirectToGithubAuthorizeUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GithubCallback(ctx context.Context, in *GithubCallbackRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_GithubCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LinkGitHub(ctx context.Context, in *LinkGitHubRequest, opts ...grpc.CallOption) (*RedirectToGithubAuthorizeUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedirectToGithubAuthorizeUrlResponse)
	err := c.cc.Invoke(ctx, AuthService_LinkGitHub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UnlinkGitHub(ctx context.Context, in *UnlinkGitHubRequest, opts ...grpc.CallOption) (*UnlinkGitHubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkGitHubResponse)
	err := c.cc.Invoke(ctx, AuthService_UnlinkGitHub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	// --- Local account / 本地账号登录 ---
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// Refresh access token using refresh_token
	// 使用 refresh_token 刷新 access_token
	RefreshToken(context.Context, *RefreshTokenRequest) (*LoginResponse, error)
	// --- Github OAuth2 authorization code flow / Github 授权登录 ---
	// Step1: client redirect to Github authorize_url
	// 第一步: 客户端重定向到 Github 授权页面
	RedirectToGithubAuthorizeUrl(context.Context, *RedirectToGithubAuthorizeUrlRequest) (*RedirectToGithubAuthorizeUrlResponse, error)
	// Step2: client sends code from callback; server exchanges token and issues app session
	// 第二步: 客户端提交回调 code，服务端换 token 并签发应用会话
	GithubCallback(context.Context, *GithubCallbackRequest) (*LoginResponse, error)
	// Step 1 for logged-in user binding GitHub
	// 已登录用户绑定 GitHub：第一步获取授权 URL
	LinkGitHub(context.Context, *LinkGitHubRequest) (*RedirectToGithubAuthorizeUrlResponse, error)
	// Unbind GitHub from current user
	// 解绑当前用户的 GitHub 账号
	UnlinkGitHub(context.Context, *UnlinkGitHubRequest) (*UnlinkGitHubResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) RedirectToGithubAuthorizeUrl(context.Context, *RedirectToGithubAuthorizeUrlRequest) (*RedirectToGithubAuthorizeUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RedirectToGithubAuthorizeUrl not implemented")
}
func (UnimplementedAuthServiceServer) GithubCallback(context.Context, *GithubCallbackRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GithubCallback not implemented")
}
func (UnimplementedAuthServiceServer) LinkGitHub(context.Context, *LinkGitHubRequest) (*RedirectToGithubAuthorizeUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkGitHub not implemented")
}
func (UnimplementedAuthServiceServer) UnlinkGitHub(context.Context, *UnlinkGitHubRequest) (*UnlinkGitHubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkGitHub not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RedirectToGithubAuthorizeUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectToGithubAuthorizeUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RedirectToGithubAuthorizeUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RedirectToGithubAuthorizeUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RedirectToGithubAuthorizeUrl(ctx, req.(*RedirectToGithubAuthorizeUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GithubCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GithubCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GithubCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GithubCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GithubCallback(ctx, req.(*GithubCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LinkGitHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkGitHubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LinkGitHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LinkGitHub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LinkGitHub(ctx, req.(*LinkGitHubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UnlinkGitHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkGitHubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UnlinkGitHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UnlinkGitHub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UnlinkGitHub(ctx, req.(*UnlinkGitHubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beehive_im.auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
		{
			MethodName: "RedirectToGithubAuthorizeUrl",
			Handler:    _AuthService_RedirectToGithubAuthorizeUrl_Handler,
		},
		{
			MethodName: "GithubCallback",
			Handler:    _AuthService_GithubCallback_Handler,
		},
		{
			MethodName: "LinkGitHub",
			Handler:    _AuthService_LinkGitHub_Handler,
		},
		{
			MethodName: "UnlinkGitHub",
			Handler:    _AuthService_UnlinkGitHub_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
