// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: notification.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/notification/internal/logic"
	"github.com/HappyLadySauce/Beehive-IM/services/notification/internal/svc"
	"github.com/HappyLadySauce/Beehive-IM/services/notification/pb"
)

type NotificationServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedNotificationServiceServer
}

func NewNotificationServiceServer(svcCtx *svc.ServiceContext) *NotificationServiceServer {
	return &NotificationServiceServer{
		svcCtx: svcCtx,
	}
}

// Health returns service liveness for operational checks.
func (s *NotificationServiceServer) Health(ctx context.Context, in *pb.HealthRequest) (*pb.HealthResponse, error) {
	l := logic.NewHealthLogic(ctx, s.svcCtx)
	return l.Health(in)
}
