// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: presence.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/presence/internal/logic"
	"github.com/HappyLadySauce/Beehive-IM/services/presence/internal/svc"
	"github.com/HappyLadySauce/Beehive-IM/services/presence/pb"
)

type PresenceServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPresenceServiceServer
}

func NewPresenceServiceServer(svcCtx *svc.ServiceContext) *PresenceServiceServer {
	return &PresenceServiceServer{
		svcCtx: svcCtx,
	}
}

// UpsertConnection registers or replaces an online connection.
func (s *PresenceServiceServer) UpsertConnection(ctx context.Context, in *pb.UpsertConnectionRequest) (*pb.UpsertConnectionResponse, error) {
	l := logic.NewUpsertConnectionLogic(ctx, s.svcCtx)
	return l.UpsertConnection(in)
}

// RefreshConnection refreshes online connection TTL.
func (s *PresenceServiceServer) RefreshConnection(ctx context.Context, in *pb.RefreshConnectionRequest) (*pb.RefreshConnectionResponse, error) {
	l := logic.NewRefreshConnectionLogic(ctx, s.svcCtx)
	return l.RefreshConnection(in)
}

// RebindGateway updates the current upstream gateway route.
func (s *PresenceServiceServer) RebindGateway(ctx context.Context, in *pb.RebindGatewayRequest) (*pb.RebindGatewayResponse, error) {
	l := logic.NewRebindGatewayLogic(ctx, s.svcCtx)
	return l.RebindGateway(in)
}

// RemoveConnection removes an online connection if ownership still matches.
func (s *PresenceServiceServer) RemoveConnection(ctx context.Context, in *pb.RemoveConnectionRequest) (*pb.RemoveConnectionResponse, error) {
	l := logic.NewRemoveConnectionLogic(ctx, s.svcCtx)
	return l.RemoveConnection(in)
}

// GetLiveRoutes returns live routes for one user.
func (s *PresenceServiceServer) GetLiveRoutes(ctx context.Context, in *pb.GetLiveRoutesRequest) (*pb.GetLiveRoutesResponse, error) {
	l := logic.NewGetLiveRoutesLogic(ctx, s.svcCtx)
	return l.GetLiveRoutes(in)
}

// CleanupEdge removes stale routes owned by one edge.
func (s *PresenceServiceServer) CleanupEdge(ctx context.Context, in *pb.CleanupEdgeRequest) (*pb.CleanupEdgeResponse, error) {
	l := logic.NewCleanupEdgeLogic(ctx, s.svcCtx)
	return l.CleanupEdge(in)
}
