// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: presence.proto

package presenceservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/presence/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CleanupEdgeRequest        = pb.CleanupEdgeRequest
	CleanupEdgeResponse       = pb.CleanupEdgeResponse
	ConnectionMeta            = pb.ConnectionMeta
	GetLiveRoutesRequest      = pb.GetLiveRoutesRequest
	GetLiveRoutesResponse     = pb.GetLiveRoutesResponse
	RebindGatewayRequest      = pb.RebindGatewayRequest
	RebindGatewayResponse     = pb.RebindGatewayResponse
	RefreshConnectionRequest  = pb.RefreshConnectionRequest
	RefreshConnectionResponse = pb.RefreshConnectionResponse
	RemoveConnectionRequest   = pb.RemoveConnectionRequest
	RemoveConnectionResponse  = pb.RemoveConnectionResponse
	UpsertConnectionRequest   = pb.UpsertConnectionRequest
	UpsertConnectionResponse  = pb.UpsertConnectionResponse

	PresenceService interface {
		// UpsertConnection registers or replaces an online connection.
		UpsertConnection(ctx context.Context, in *UpsertConnectionRequest, opts ...grpc.CallOption) (*UpsertConnectionResponse, error)
		// RefreshConnection refreshes online connection TTL.
		RefreshConnection(ctx context.Context, in *RefreshConnectionRequest, opts ...grpc.CallOption) (*RefreshConnectionResponse, error)
		// RebindGateway updates the current upstream gateway route.
		RebindGateway(ctx context.Context, in *RebindGatewayRequest, opts ...grpc.CallOption) (*RebindGatewayResponse, error)
		// RemoveConnection removes an online connection if ownership still matches.
		RemoveConnection(ctx context.Context, in *RemoveConnectionRequest, opts ...grpc.CallOption) (*RemoveConnectionResponse, error)
		// GetLiveRoutes returns live routes for one user.
		GetLiveRoutes(ctx context.Context, in *GetLiveRoutesRequest, opts ...grpc.CallOption) (*GetLiveRoutesResponse, error)
		// CleanupEdge removes stale routes owned by one edge.
		CleanupEdge(ctx context.Context, in *CleanupEdgeRequest, opts ...grpc.CallOption) (*CleanupEdgeResponse, error)
	}

	defaultPresenceService struct {
		cli zrpc.Client
	}
)

func NewPresenceService(cli zrpc.Client) PresenceService {
	return &defaultPresenceService{
		cli: cli,
	}
}

// UpsertConnection registers or replaces an online connection.
func (m *defaultPresenceService) UpsertConnection(ctx context.Context, in *UpsertConnectionRequest, opts ...grpc.CallOption) (*UpsertConnectionResponse, error) {
	client := pb.NewPresenceServiceClient(m.cli.Conn())
	return client.UpsertConnection(ctx, in, opts...)
}

// RefreshConnection refreshes online connection TTL.
func (m *defaultPresenceService) RefreshConnection(ctx context.Context, in *RefreshConnectionRequest, opts ...grpc.CallOption) (*RefreshConnectionResponse, error) {
	client := pb.NewPresenceServiceClient(m.cli.Conn())
	return client.RefreshConnection(ctx, in, opts...)
}

// RebindGateway updates the current upstream gateway route.
func (m *defaultPresenceService) RebindGateway(ctx context.Context, in *RebindGatewayRequest, opts ...grpc.CallOption) (*RebindGatewayResponse, error) {
	client := pb.NewPresenceServiceClient(m.cli.Conn())
	return client.RebindGateway(ctx, in, opts...)
}

// RemoveConnection removes an online connection if ownership still matches.
func (m *defaultPresenceService) RemoveConnection(ctx context.Context, in *RemoveConnectionRequest, opts ...grpc.CallOption) (*RemoveConnectionResponse, error) {
	client := pb.NewPresenceServiceClient(m.cli.Conn())
	return client.RemoveConnection(ctx, in, opts...)
}

// GetLiveRoutes returns live routes for one user.
func (m *defaultPresenceService) GetLiveRoutes(ctx context.Context, in *GetLiveRoutesRequest, opts ...grpc.CallOption) (*GetLiveRoutesResponse, error) {
	client := pb.NewPresenceServiceClient(m.cli.Conn())
	return client.GetLiveRoutes(ctx, in, opts...)
}

// CleanupEdge removes stale routes owned by one edge.
func (m *defaultPresenceService) CleanupEdge(ctx context.Context, in *CleanupEdgeRequest, opts ...grpc.CallOption) (*CleanupEdgeResponse, error) {
	client := pb.NewPresenceServiceClient(m.cli.Conn())
	return client.CleanupEdge(ctx, in, opts...)
}
