// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: notification.proto

package notificationservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/notification/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HealthRequest  = pb.HealthRequest
	HealthResponse = pb.HealthResponse

	NotificationService interface {
		// Health returns service liveness for operational checks.
		Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	}

	defaultNotificationService struct {
		cli zrpc.Client
	}
)

func NewNotificationService(cli zrpc.Client) NotificationService {
	return &defaultNotificationService{
		cli: cli,
	}
}

// Health returns service liveness for operational checks.
func (m *defaultNotificationService) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.Health(ctx, in, opts...)
}
