// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: message.proto

package messageservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/message/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AckMessagesRequest               = pb.AckMessagesRequest
	AckMessagesResponse              = pb.AckMessagesResponse
	ConversationCursor               = pb.ConversationCursor
	ConversationSummary              = pb.ConversationSummary
	ConversationSummaryCursor        = pb.ConversationSummaryCursor
	ConversationSyncResult           = pb.ConversationSyncResult
	GetConversationSummariesRequest  = pb.GetConversationSummariesRequest
	GetConversationSummariesResponse = pb.GetConversationSummariesResponse
	ListMessagesRequest              = pb.ListMessagesRequest
	ListMessagesResponse             = pb.ListMessagesResponse
	MessageItem                      = pb.MessageItem
	SendMessageRequest               = pb.SendMessageRequest
	SendMessageResponse              = pb.SendMessageResponse
	SyncMessagesRequest              = pb.SyncMessagesRequest
	SyncMessagesResponse             = pb.SyncMessagesResponse

	MessageService interface {
		// SendMessage validates permissions and persists one client message.
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
		// AckMessages records delivered/read receipts for message sequences.
		AckMessages(ctx context.Context, in *AckMessagesRequest, opts ...grpc.CallOption) (*AckMessagesResponse, error)
		// ListMessages returns one conversation history page.
		ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
		// SyncMessages returns missing messages for multiple conversations.
		SyncMessages(ctx context.Context, in *SyncMessagesRequest, opts ...grpc.CallOption) (*SyncMessagesResponse, error)
		// GetConversationSummaries returns last message and unread count for conversations.
		GetConversationSummaries(ctx context.Context, in *GetConversationSummariesRequest, opts ...grpc.CallOption) (*GetConversationSummariesResponse, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

// SendMessage validates permissions and persists one client message.
func (m *defaultMessageService) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

// AckMessages records delivered/read receipts for message sequences.
func (m *defaultMessageService) AckMessages(ctx context.Context, in *AckMessagesRequest, opts ...grpc.CallOption) (*AckMessagesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.AckMessages(ctx, in, opts...)
}

// ListMessages returns one conversation history page.
func (m *defaultMessageService) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.ListMessages(ctx, in, opts...)
}

// SyncMessages returns missing messages for multiple conversations.
func (m *defaultMessageService) SyncMessages(ctx context.Context, in *SyncMessagesRequest, opts ...grpc.CallOption) (*SyncMessagesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SyncMessages(ctx, in, opts...)
}

// GetConversationSummaries returns last message and unread count for conversations.
func (m *defaultMessageService) GetConversationSummaries(ctx context.Context, in *GetConversationSummariesRequest, opts ...grpc.CallOption) (*GetConversationSummariesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetConversationSummaries(ctx, in, opts...)
}
