// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: message.proto

package messageservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/message/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AckMessagesRequest  = pb.AckMessagesRequest
	AckMessagesResponse = pb.AckMessagesResponse
	SendMessageRequest  = pb.SendMessageRequest
	SendMessageResponse = pb.SendMessageResponse

	MessageService interface {
		// SendMessage validates permissions and persists one client message.
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
		// AckMessages records delivered/read receipts for message sequences.
		AckMessages(ctx context.Context, in *AckMessagesRequest, opts ...grpc.CallOption) (*AckMessagesResponse, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

// SendMessage validates permissions and persists one client message.
func (m *defaultMessageService) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

// AckMessages records delivered/read receipts for message sequences.
func (m *defaultMessageService) AckMessages(ctx context.Context, in *AckMessagesRequest, opts ...grpc.CallOption) (*AckMessagesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.AckMessages(ctx, in, opts...)
}
