// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: presence.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PresenceService_UpsertConnection_FullMethodName  = "/beehive_im.presence.PresenceService/UpsertConnection"
	PresenceService_RefreshConnection_FullMethodName = "/beehive_im.presence.PresenceService/RefreshConnection"
	PresenceService_RebindGateway_FullMethodName     = "/beehive_im.presence.PresenceService/RebindGateway"
	PresenceService_RemoveConnection_FullMethodName  = "/beehive_im.presence.PresenceService/RemoveConnection"
	PresenceService_GetLiveRoutes_FullMethodName     = "/beehive_im.presence.PresenceService/GetLiveRoutes"
	PresenceService_CleanupEdge_FullMethodName       = "/beehive_im.presence.PresenceService/CleanupEdge"
)

// PresenceServiceClient is the client API for PresenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PresenceServiceClient interface {
	// UpsertConnection registers or replaces an online connection.
	// UpsertConnection 注册或覆盖一个在线连接。
	UpsertConnection(ctx context.Context, in *UpsertConnectionRequest, opts ...grpc.CallOption) (*UpsertConnectionResponse, error)
	// RefreshConnection refreshes online connection TTL.
	// RefreshConnection 续期在线连接 TTL。
	RefreshConnection(ctx context.Context, in *RefreshConnectionRequest, opts ...grpc.CallOption) (*RefreshConnectionResponse, error)
	// RebindGateway updates the current upstream gateway route.
	// RebindGateway 更新当前上游 Gateway 路由。
	RebindGateway(ctx context.Context, in *RebindGatewayRequest, opts ...grpc.CallOption) (*RebindGatewayResponse, error)
	// RemoveConnection removes an online connection if ownership still matches.
	// RemoveConnection 在归属仍匹配时移除在线连接。
	RemoveConnection(ctx context.Context, in *RemoveConnectionRequest, opts ...grpc.CallOption) (*RemoveConnectionResponse, error)
	// GetLiveRoutes returns live routes for one user.
	// GetLiveRoutes 返回单个用户的在线路由。
	GetLiveRoutes(ctx context.Context, in *GetLiveRoutesRequest, opts ...grpc.CallOption) (*GetLiveRoutesResponse, error)
	// CleanupEdge removes stale routes owned by one edge.
	// CleanupEdge 清理某个 Edge 拥有的残留路由。
	CleanupEdge(ctx context.Context, in *CleanupEdgeRequest, opts ...grpc.CallOption) (*CleanupEdgeResponse, error)
}

type presenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceServiceClient(cc grpc.ClientConnInterface) PresenceServiceClient {
	return &presenceServiceClient{cc}
}

func (c *presenceServiceClient) UpsertConnection(ctx context.Context, in *UpsertConnectionRequest, opts ...grpc.CallOption) (*UpsertConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertConnectionResponse)
	err := c.cc.Invoke(ctx, PresenceService_UpsertConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) RefreshConnection(ctx context.Context, in *RefreshConnectionRequest, opts ...grpc.CallOption) (*RefreshConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshConnectionResponse)
	err := c.cc.Invoke(ctx, PresenceService_RefreshConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) RebindGateway(ctx context.Context, in *RebindGatewayRequest, opts ...grpc.CallOption) (*RebindGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebindGatewayResponse)
	err := c.cc.Invoke(ctx, PresenceService_RebindGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) RemoveConnection(ctx context.Context, in *RemoveConnectionRequest, opts ...grpc.CallOption) (*RemoveConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveConnectionResponse)
	err := c.cc.Invoke(ctx, PresenceService_RemoveConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) GetLiveRoutes(ctx context.Context, in *GetLiveRoutesRequest, opts ...grpc.CallOption) (*GetLiveRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLiveRoutesResponse)
	err := c.cc.Invoke(ctx, PresenceService_GetLiveRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) CleanupEdge(ctx context.Context, in *CleanupEdgeRequest, opts ...grpc.CallOption) (*CleanupEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupEdgeResponse)
	err := c.cc.Invoke(ctx, PresenceService_CleanupEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PresenceServiceServer is the server API for PresenceService service.
// All implementations must embed UnimplementedPresenceServiceServer
// for forward compatibility.
type PresenceServiceServer interface {
	// UpsertConnection registers or replaces an online connection.
	// UpsertConnection 注册或覆盖一个在线连接。
	UpsertConnection(context.Context, *UpsertConnectionRequest) (*UpsertConnectionResponse, error)
	// RefreshConnection refreshes online connection TTL.
	// RefreshConnection 续期在线连接 TTL。
	RefreshConnection(context.Context, *RefreshConnectionRequest) (*RefreshConnectionResponse, error)
	// RebindGateway updates the current upstream gateway route.
	// RebindGateway 更新当前上游 Gateway 路由。
	RebindGateway(context.Context, *RebindGatewayRequest) (*RebindGatewayResponse, error)
	// RemoveConnection removes an online connection if ownership still matches.
	// RemoveConnection 在归属仍匹配时移除在线连接。
	RemoveConnection(context.Context, *RemoveConnectionRequest) (*RemoveConnectionResponse, error)
	// GetLiveRoutes returns live routes for one user.
	// GetLiveRoutes 返回单个用户的在线路由。
	GetLiveRoutes(context.Context, *GetLiveRoutesRequest) (*GetLiveRoutesResponse, error)
	// CleanupEdge removes stale routes owned by one edge.
	// CleanupEdge 清理某个 Edge 拥有的残留路由。
	CleanupEdge(context.Context, *CleanupEdgeRequest) (*CleanupEdgeResponse, error)
	mustEmbedUnimplementedPresenceServiceServer()
}

// UnimplementedPresenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPresenceServiceServer struct{}

func (UnimplementedPresenceServiceServer) UpsertConnection(context.Context, *UpsertConnectionRequest) (*UpsertConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertConnection not implemented")
}
func (UnimplementedPresenceServiceServer) RefreshConnection(context.Context, *RefreshConnectionRequest) (*RefreshConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshConnection not implemented")
}
func (UnimplementedPresenceServiceServer) RebindGateway(context.Context, *RebindGatewayRequest) (*RebindGatewayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebindGateway not implemented")
}
func (UnimplementedPresenceServiceServer) RemoveConnection(context.Context, *RemoveConnectionRequest) (*RemoveConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveConnection not implemented")
}
func (UnimplementedPresenceServiceServer) GetLiveRoutes(context.Context, *GetLiveRoutesRequest) (*GetLiveRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLiveRoutes not implemented")
}
func (UnimplementedPresenceServiceServer) CleanupEdge(context.Context, *CleanupEdgeRequest) (*CleanupEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupEdge not implemented")
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}
func (UnimplementedPresenceServiceServer) testEmbeddedByValue()                         {}

// UnsafePresenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServiceServer will
// result in compilation errors.
type UnsafePresenceServiceServer interface {
	mustEmbedUnimplementedPresenceServiceServer()
}

func RegisterPresenceServiceServer(s grpc.ServiceRegistrar, srv PresenceServiceServer) {
	// If the following call panics, it indicates UnimplementedPresenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PresenceService_ServiceDesc, srv)
}

func _PresenceService_UpsertConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).UpsertConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_UpsertConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).UpsertConnection(ctx, req.(*UpsertConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_RefreshConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).RefreshConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_RefreshConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).RefreshConnection(ctx, req.(*RefreshConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_RebindGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebindGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).RebindGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_RebindGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).RebindGateway(ctx, req.(*RebindGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_RemoveConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).RemoveConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_RemoveConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).RemoveConnection(ctx, req.(*RemoveConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_GetLiveRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiveRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).GetLiveRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_GetLiveRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).GetLiveRoutes(ctx, req.(*GetLiveRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_CleanupEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).CleanupEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_CleanupEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).CleanupEdge(ctx, req.(*CleanupEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PresenceService_ServiceDesc is the grpc.ServiceDesc for PresenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PresenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beehive_im.presence.PresenceService",
	HandlerType: (*PresenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertConnection",
			Handler:    _PresenceService_UpsertConnection_Handler,
		},
		{
			MethodName: "RefreshConnection",
			Handler:    _PresenceService_RefreshConnection_Handler,
		},
		{
			MethodName: "RebindGateway",
			Handler:    _PresenceService_RebindGateway_Handler,
		},
		{
			MethodName: "RemoveConnection",
			Handler:    _PresenceService_RemoveConnection_Handler,
		},
		{
			MethodName: "GetLiveRoutes",
			Handler:    _PresenceService_GetLiveRoutes_Handler,
		},
		{
			MethodName: "CleanupEdge",
			Handler:    _PresenceService_CleanupEdge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "presence.proto",
}
