// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: presence.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId           string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	EdgeId           string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	UserId           string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId         string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	GatewayId        string                 `protobuf:"bytes,6,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	LastClientSeq    int64                  `protobuf:"varint,7,opt,name=last_client_seq,json=lastClientSeq,proto3" json:"last_client_seq,omitempty"`
	LastDeliveredSeq int64                  `protobuf:"varint,8,opt,name=last_delivered_seq,json=lastDeliveredSeq,proto3" json:"last_delivered_seq,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionMeta) Reset() {
	*x = ConnectionMeta{}
	mi := &file_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMeta) ProtoMessage() {}

func (x *ConnectionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMeta.ProtoReflect.Descriptor instead.
func (*ConnectionMeta) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionMeta) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectionMeta) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *ConnectionMeta) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *ConnectionMeta) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectionMeta) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ConnectionMeta) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ConnectionMeta) GetLastClientSeq() int64 {
	if x != nil {
		return x.LastClientSeq
	}
	return 0
}

func (x *ConnectionMeta) GetLastDeliveredSeq() int64 {
	if x != nil {
		return x.LastDeliveredSeq
	}
	return 0
}

type UpsertConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *ConnectionMeta        `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertConnectionRequest) Reset() {
	*x = UpsertConnectionRequest{}
	mi := &file_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertConnectionRequest) ProtoMessage() {}

func (x *UpsertConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertConnectionRequest.ProtoReflect.Descriptor instead.
func (*UpsertConnectionRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertConnectionRequest) GetConnection() *ConnectionMeta {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *UpsertConnectionRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type UpsertConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertConnectionResponse) Reset() {
	*x = UpsertConnectionResponse{}
	mi := &file_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertConnectionResponse) ProtoMessage() {}

func (x *UpsertConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertConnectionResponse.ProtoReflect.Descriptor instead.
func (*UpsertConnectionResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertConnectionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UpsertConnectionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UpsertConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RefreshConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshConnectionRequest) Reset() {
	*x = RefreshConnectionRequest{}
	mi := &file_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshConnectionRequest) ProtoMessage() {}

func (x *RefreshConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshConnectionRequest.ProtoReflect.Descriptor instead.
func (*RefreshConnectionRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshConnectionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RefreshConnectionRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *RefreshConnectionRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *RefreshConnectionRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type RefreshConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refreshed     bool                   `protobuf:"varint,1,opt,name=refreshed,proto3" json:"refreshed,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshConnectionResponse) Reset() {
	*x = RefreshConnectionResponse{}
	mi := &file_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshConnectionResponse) ProtoMessage() {}

func (x *RefreshConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshConnectionResponse.ProtoReflect.Descriptor instead.
func (*RefreshConnectionResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshConnectionResponse) GetRefreshed() bool {
	if x != nil {
		return x.Refreshed
	}
	return false
}

func (x *RefreshConnectionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RefreshConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RebindGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,3,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	GatewayId     string                 `protobuf:"bytes,4,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebindGatewayRequest) Reset() {
	*x = RebindGatewayRequest{}
	mi := &file_presence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebindGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebindGatewayRequest) ProtoMessage() {}

func (x *RebindGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebindGatewayRequest.ProtoReflect.Descriptor instead.
func (*RebindGatewayRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{5}
}

func (x *RebindGatewayRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RebindGatewayRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *RebindGatewayRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *RebindGatewayRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *RebindGatewayRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type RebindGatewayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rebound       bool                   `protobuf:"varint,1,opt,name=rebound,proto3" json:"rebound,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebindGatewayResponse) Reset() {
	*x = RebindGatewayResponse{}
	mi := &file_presence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebindGatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebindGatewayResponse) ProtoMessage() {}

func (x *RebindGatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebindGatewayResponse.ProtoReflect.Descriptor instead.
func (*RebindGatewayResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{6}
}

func (x *RebindGatewayResponse) GetRebound() bool {
	if x != nil {
		return x.Rebound
	}
	return false
}

func (x *RebindGatewayResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RebindGatewayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *ConnectionMeta        `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConnectionRequest) Reset() {
	*x = RemoveConnectionRequest{}
	mi := &file_presence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConnectionRequest) ProtoMessage() {}

func (x *RemoveConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConnectionRequest.ProtoReflect.Descriptor instead.
func (*RemoveConnectionRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveConnectionRequest) GetConnection() *ConnectionMeta {
	if x != nil {
		return x.Connection
	}
	return nil
}

type RemoveConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConnectionResponse) Reset() {
	*x = RemoveConnectionResponse{}
	mi := &file_presence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConnectionResponse) ProtoMessage() {}

func (x *RemoveConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConnectionResponse.ProtoReflect.Descriptor instead.
func (*RemoveConnectionResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveConnectionResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type GetLiveRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveRoutesRequest) Reset() {
	*x = GetLiveRoutesRequest{}
	mi := &file_presence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveRoutesRequest) ProtoMessage() {}

func (x *GetLiveRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetLiveRoutesRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{9}
}

func (x *GetLiveRoutesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLiveRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*ConnectionMeta      `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveRoutesResponse) Reset() {
	*x = GetLiveRoutesResponse{}
	mi := &file_presence_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveRoutesResponse) ProtoMessage() {}

func (x *GetLiveRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveRoutesResponse.ProtoReflect.Descriptor instead.
func (*GetLiveRoutesResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{10}
}

func (x *GetLiveRoutesResponse) GetRoutes() []*ConnectionMeta {
	if x != nil {
		return x.Routes
	}
	return nil
}

type CleanupEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	BatchSize     int32                  `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupEdgeRequest) Reset() {
	*x = CleanupEdgeRequest{}
	mi := &file_presence_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupEdgeRequest) ProtoMessage() {}

func (x *CleanupEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupEdgeRequest.ProtoReflect.Descriptor instead.
func (*CleanupEdgeRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{11}
}

func (x *CleanupEdgeRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *CleanupEdgeRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type CleanupEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       int32                  `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupEdgeResponse) Reset() {
	*x = CleanupEdgeResponse{}
	mi := &file_presence_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupEdgeResponse) ProtoMessage() {}

func (x *CleanupEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupEdgeResponse.ProtoReflect.Descriptor instead.
func (*CleanupEdgeResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{12}
}

func (x *CleanupEdgeResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

var File_presence_proto protoreflect.FileDescriptor

const file_presence_proto_rawDesc = "" +
	"\n" +
	"\x0epresence.proto\x12\x13beehive_im.presence\"\x8c\x02\n" +
	"\x0eConnectionMeta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x06 \x01(\tR\tgatewayId\x12&\n" +
	"\x0flast_client_seq\x18\a \x01(\x03R\rlastClientSeq\x12,\n" +
	"\x12last_delivered_seq\x18\b \x01(\x03R\x10lastDeliveredSeq\"\x7f\n" +
	"\x17UpsertConnectionRequest\x12C\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2#.beehive_im.presence.ConnectionMetaR\n" +
	"connection\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"o\n" +
	"\x18UpsertConnectionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8c\x01\n" +
	"\x18RefreshConnectionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\"r\n" +
	"\x19RefreshConnectionResponse\x12\x1c\n" +
	"\trefreshed\x18\x01 \x01(\bR\trefreshed\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa7\x01\n" +
	"\x14RebindGatewayRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x17\n" +
	"\aedge_id\x18\x03 \x01(\tR\x06edgeId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x04 \x01(\tR\tgatewayId\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\"j\n" +
	"\x15RebindGatewayResponse\x12\x18\n" +
	"\arebound\x18\x01 \x01(\bR\arebound\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"^\n" +
	"\x17RemoveConnectionRequest\x12C\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2#.beehive_im.presence.ConnectionMetaR\n" +
	"connection\"4\n" +
	"\x18RemoveConnectionResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"/\n" +
	"\x14GetLiveRoutesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"T\n" +
	"\x15GetLiveRoutesResponse\x12;\n" +
	"\x06routes\x18\x01 \x03(\v2#.beehive_im.presence.ConnectionMetaR\x06routes\"L\n" +
	"\x12CleanupEdgeRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\x05R\tbatchSize\"/\n" +
	"\x13CleanupEdgeResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\x05R\aremoved2\x99\x05\n" +
	"\x0fPresenceService\x12o\n" +
	"\x10UpsertConnection\x12,.beehive_im.presence.UpsertConnectionRequest\x1a-.beehive_im.presence.UpsertConnectionResponse\x12r\n" +
	"\x11RefreshConnection\x12-.beehive_im.presence.RefreshConnectionRequest\x1a..beehive_im.presence.RefreshConnectionResponse\x12f\n" +
	"\rRebindGateway\x12).beehive_im.presence.RebindGatewayRequest\x1a*.beehive_im.presence.RebindGatewayResponse\x12o\n" +
	"\x10RemoveConnection\x12,.beehive_im.presence.RemoveConnectionRequest\x1a-.beehive_im.presence.RemoveConnectionResponse\x12f\n" +
	"\rGetLiveRoutes\x12).beehive_im.presence.GetLiveRoutesRequest\x1a*.beehive_im.presence.GetLiveRoutesResponse\x12`\n" +
	"\vCleanupEdge\x12'.beehive_im.presence.CleanupEdgeRequest\x1a(.beehive_im.presence.CleanupEdgeResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_presence_proto_rawDescOnce sync.Once
	file_presence_proto_rawDescData []byte
)

func file_presence_proto_rawDescGZIP() []byte {
	file_presence_proto_rawDescOnce.Do(func() {
		file_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_presence_proto_rawDesc), len(file_presence_proto_rawDesc)))
	})
	return file_presence_proto_rawDescData
}

var file_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_presence_proto_goTypes = []any{
	(*ConnectionMeta)(nil),            // 0: beehive_im.presence.ConnectionMeta
	(*UpsertConnectionRequest)(nil),   // 1: beehive_im.presence.UpsertConnectionRequest
	(*UpsertConnectionResponse)(nil),  // 2: beehive_im.presence.UpsertConnectionResponse
	(*RefreshConnectionRequest)(nil),  // 3: beehive_im.presence.RefreshConnectionRequest
	(*RefreshConnectionResponse)(nil), // 4: beehive_im.presence.RefreshConnectionResponse
	(*RebindGatewayRequest)(nil),      // 5: beehive_im.presence.RebindGatewayRequest
	(*RebindGatewayResponse)(nil),     // 6: beehive_im.presence.RebindGatewayResponse
	(*RemoveConnectionRequest)(nil),   // 7: beehive_im.presence.RemoveConnectionRequest
	(*RemoveConnectionResponse)(nil),  // 8: beehive_im.presence.RemoveConnectionResponse
	(*GetLiveRoutesRequest)(nil),      // 9: beehive_im.presence.GetLiveRoutesRequest
	(*GetLiveRoutesResponse)(nil),     // 10: beehive_im.presence.GetLiveRoutesResponse
	(*CleanupEdgeRequest)(nil),        // 11: beehive_im.presence.CleanupEdgeRequest
	(*CleanupEdgeResponse)(nil),       // 12: beehive_im.presence.CleanupEdgeResponse
}
var file_presence_proto_depIdxs = []int32{
	0,  // 0: beehive_im.presence.UpsertConnectionRequest.connection:type_name -> beehive_im.presence.ConnectionMeta
	0,  // 1: beehive_im.presence.RemoveConnectionRequest.connection:type_name -> beehive_im.presence.ConnectionMeta
	0,  // 2: beehive_im.presence.GetLiveRoutesResponse.routes:type_name -> beehive_im.presence.ConnectionMeta
	1,  // 3: beehive_im.presence.PresenceService.UpsertConnection:input_type -> beehive_im.presence.UpsertConnectionRequest
	3,  // 4: beehive_im.presence.PresenceService.RefreshConnection:input_type -> beehive_im.presence.RefreshConnectionRequest
	5,  // 5: beehive_im.presence.PresenceService.RebindGateway:input_type -> beehive_im.presence.RebindGatewayRequest
	7,  // 6: beehive_im.presence.PresenceService.RemoveConnection:input_type -> beehive_im.presence.RemoveConnectionRequest
	9,  // 7: beehive_im.presence.PresenceService.GetLiveRoutes:input_type -> beehive_im.presence.GetLiveRoutesRequest
	11, // 8: beehive_im.presence.PresenceService.CleanupEdge:input_type -> beehive_im.presence.CleanupEdgeRequest
	2,  // 9: beehive_im.presence.PresenceService.UpsertConnection:output_type -> beehive_im.presence.UpsertConnectionResponse
	4,  // 10: beehive_im.presence.PresenceService.RefreshConnection:output_type -> beehive_im.presence.RefreshConnectionResponse
	6,  // 11: beehive_im.presence.PresenceService.RebindGateway:output_type -> beehive_im.presence.RebindGatewayResponse
	8,  // 12: beehive_im.presence.PresenceService.RemoveConnection:output_type -> beehive_im.presence.RemoveConnectionResponse
	10, // 13: beehive_im.presence.PresenceService.GetLiveRoutes:output_type -> beehive_im.presence.GetLiveRoutesResponse
	12, // 14: beehive_im.presence.PresenceService.CleanupEdge:output_type -> beehive_im.presence.CleanupEdgeResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_presence_proto_init() }
func file_presence_proto_init() {
	if File_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_presence_proto_rawDesc), len(file_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_presence_proto_goTypes,
		DependencyIndexes: file_presence_proto_depIdxs,
		MessageInfos:      file_presence_proto_msgTypes,
	}.Build()
	File_presence_proto = out.File
	file_presence_proto_goTypes = nil
	file_presence_proto_depIdxs = nil
}
