// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: conversation.proto

package conversationservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-IM/services/conversation/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMembersRequest                  = pb.AddMembersRequest
	AddMembersResponse                 = pb.AddMembersResponse
	AllocateMessageSeqRequest          = pb.AllocateMessageSeqRequest
	AllocateMessageSeqResponse         = pb.AllocateMessageSeqResponse
	CheckReadPermissionRequest         = pb.CheckReadPermissionRequest
	CheckReadPermissionResponse        = pb.CheckReadPermissionResponse
	CheckSendPermissionRequest         = pb.CheckSendPermissionRequest
	CheckSendPermissionResponse        = pb.CheckSendPermissionResponse
	Conversation                       = pb.Conversation
	ConversationListItem               = pb.ConversationListItem
	ConversationMember                 = pb.ConversationMember
	ConversationSettings               = pb.ConversationSettings
	CreateConversationRequest          = pb.CreateConversationRequest
	CreateConversationResponse         = pb.CreateConversationResponse
	DismissConversationRequest         = pb.DismissConversationRequest
	DismissConversationResponse        = pb.DismissConversationResponse
	GetConversationRequest             = pb.GetConversationRequest
	GetConversationResponse            = pb.GetConversationResponse
	LeaveConversationRequest           = pb.LeaveConversationRequest
	LeaveConversationResponse          = pb.LeaveConversationResponse
	ListConversationsRequest           = pb.ListConversationsRequest
	ListConversationsResponse          = pb.ListConversationsResponse
	MarkConversationReadRequest        = pb.MarkConversationReadRequest
	MarkConversationReadResponse       = pb.MarkConversationReadResponse
	MemberInput                        = pb.MemberInput
	RemoveMembersRequest               = pb.RemoveMembersRequest
	RemoveMembersResponse              = pb.RemoveMembersResponse
	ResolveMessageRecipientsRequest    = pb.ResolveMessageRecipientsRequest
	ResolveMessageRecipientsResponse   = pb.ResolveMessageRecipientsResponse
	TransferOwnerRequest               = pb.TransferOwnerRequest
	TransferOwnerResponse              = pb.TransferOwnerResponse
	UpdateConversationSettingsRequest  = pb.UpdateConversationSettingsRequest
	UpdateConversationSettingsResponse = pb.UpdateConversationSettingsResponse
	UpdateMemberRoleRequest            = pb.UpdateMemberRoleRequest
	UpdateMemberRoleResponse           = pb.UpdateMemberRoleResponse

	ConversationService interface {
		// CreateConversation creates a conversation and initial members.
		CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*CreateConversationResponse, error)
		// GetConversation returns one conversation with members and user settings.
		GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error)
		// ListConversations returns conversations joined by one user.
		ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
		// AddMembers adds or reactivates members in a conversation.
		AddMembers(ctx context.Context, in *AddMembersRequest, opts ...grpc.CallOption) (*AddMembersResponse, error)
		// RemoveMembers marks members as removed from a conversation.
		RemoveMembers(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*RemoveMembersResponse, error)
		// LeaveConversation lets one member leave a group conversation.
		LeaveConversation(ctx context.Context, in *LeaveConversationRequest, opts ...grpc.CallOption) (*LeaveConversationResponse, error)
		// DismissConversation closes a group conversation by owner.
		DismissConversation(ctx context.Context, in *DismissConversationRequest, opts ...grpc.CallOption) (*DismissConversationResponse, error)
		// TransferOwner transfers group ownership to another active member.
		TransferOwner(ctx context.Context, in *TransferOwnerRequest, opts ...grpc.CallOption) (*TransferOwnerResponse, error)
		// UpdateMemberRole changes one member role.
		UpdateMemberRole(ctx context.Context, in *UpdateMemberRoleRequest, opts ...grpc.CallOption) (*UpdateMemberRoleResponse, error)
		// UpdateConversationSettings updates settings owned by one user.
		UpdateConversationSettings(ctx context.Context, in *UpdateConversationSettingsRequest, opts ...grpc.CallOption) (*UpdateConversationSettingsResponse, error)
		// MarkConversationRead advances one member read or delivered cursor.
		MarkConversationRead(ctx context.Context, in *MarkConversationReadRequest, opts ...grpc.CallOption) (*MarkConversationReadResponse, error)
		// CheckSendPermission checks whether a user can send to a conversation.
		CheckSendPermission(ctx context.Context, in *CheckSendPermissionRequest, opts ...grpc.CallOption) (*CheckSendPermissionResponse, error)
		// CheckReadPermission checks whether a user can read a conversation.
		CheckReadPermission(ctx context.Context, in *CheckReadPermissionRequest, opts ...grpc.CallOption) (*CheckReadPermissionResponse, error)
		// ResolveMessageRecipients returns active users that should receive a message event.
		ResolveMessageRecipients(ctx context.Context, in *ResolveMessageRecipientsRequest, opts ...grpc.CallOption) (*ResolveMessageRecipientsResponse, error)
		// AllocateMessageSeq atomically allocates the next conversation message sequence.
		AllocateMessageSeq(ctx context.Context, in *AllocateMessageSeqRequest, opts ...grpc.CallOption) (*AllocateMessageSeqResponse, error)
	}

	defaultConversationService struct {
		cli zrpc.Client
	}
)

func NewConversationService(cli zrpc.Client) ConversationService {
	return &defaultConversationService{
		cli: cli,
	}
}

// CreateConversation creates a conversation and initial members.
func (m *defaultConversationService) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*CreateConversationResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.CreateConversation(ctx, in, opts...)
}

// GetConversation returns one conversation with members and user settings.
func (m *defaultConversationService) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.GetConversation(ctx, in, opts...)
}

// ListConversations returns conversations joined by one user.
func (m *defaultConversationService) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.ListConversations(ctx, in, opts...)
}

// AddMembers adds or reactivates members in a conversation.
func (m *defaultConversationService) AddMembers(ctx context.Context, in *AddMembersRequest, opts ...grpc.CallOption) (*AddMembersResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.AddMembers(ctx, in, opts...)
}

// RemoveMembers marks members as removed from a conversation.
func (m *defaultConversationService) RemoveMembers(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*RemoveMembersResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.RemoveMembers(ctx, in, opts...)
}

// LeaveConversation lets one member leave a group conversation.
func (m *defaultConversationService) LeaveConversation(ctx context.Context, in *LeaveConversationRequest, opts ...grpc.CallOption) (*LeaveConversationResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.LeaveConversation(ctx, in, opts...)
}

// DismissConversation closes a group conversation by owner.
func (m *defaultConversationService) DismissConversation(ctx context.Context, in *DismissConversationRequest, opts ...grpc.CallOption) (*DismissConversationResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.DismissConversation(ctx, in, opts...)
}

// TransferOwner transfers group ownership to another active member.
func (m *defaultConversationService) TransferOwner(ctx context.Context, in *TransferOwnerRequest, opts ...grpc.CallOption) (*TransferOwnerResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.TransferOwner(ctx, in, opts...)
}

// UpdateMemberRole changes one member role.
func (m *defaultConversationService) UpdateMemberRole(ctx context.Context, in *UpdateMemberRoleRequest, opts ...grpc.CallOption) (*UpdateMemberRoleResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.UpdateMemberRole(ctx, in, opts...)
}

// UpdateConversationSettings updates settings owned by one user.
func (m *defaultConversationService) UpdateConversationSettings(ctx context.Context, in *UpdateConversationSettingsRequest, opts ...grpc.CallOption) (*UpdateConversationSettingsResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.UpdateConversationSettings(ctx, in, opts...)
}

// MarkConversationRead advances one member read or delivered cursor.
func (m *defaultConversationService) MarkConversationRead(ctx context.Context, in *MarkConversationReadRequest, opts ...grpc.CallOption) (*MarkConversationReadResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.MarkConversationRead(ctx, in, opts...)
}

// CheckSendPermission checks whether a user can send to a conversation.
func (m *defaultConversationService) CheckSendPermission(ctx context.Context, in *CheckSendPermissionRequest, opts ...grpc.CallOption) (*CheckSendPermissionResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.CheckSendPermission(ctx, in, opts...)
}

// CheckReadPermission checks whether a user can read a conversation.
func (m *defaultConversationService) CheckReadPermission(ctx context.Context, in *CheckReadPermissionRequest, opts ...grpc.CallOption) (*CheckReadPermissionResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.CheckReadPermission(ctx, in, opts...)
}

// ResolveMessageRecipients returns active users that should receive a message event.
func (m *defaultConversationService) ResolveMessageRecipients(ctx context.Context, in *ResolveMessageRecipientsRequest, opts ...grpc.CallOption) (*ResolveMessageRecipientsResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.ResolveMessageRecipients(ctx, in, opts...)
}

// AllocateMessageSeq atomically allocates the next conversation message sequence.
func (m *defaultConversationService) AllocateMessageSeq(ctx context.Context, in *AllocateMessageSeqRequest, opts ...grpc.CallOption) (*AllocateMessageSeqResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.AllocateMessageSeq(ctx, in, opts...)
}
