name: Beehive-IM
services:
  postgresql:
    image: postgres:16
    container_name: beehive-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: Beehive-IM
      POSTGRES_PASSWORD: Beehive-IM
      POSTGRES_DB: Beehive-IM
      TZ: Asia/Shanghai
      PGTZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Beehive-IM -d Beehive-IM"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - beehive-network

  redis:
    image: redis:8-alpine
    container_name: beehive-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ../../data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5  
    networks:
      - beehive-network

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: beehive-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      TZ: Asia/Shanghai
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ../../data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - beehive-network

networks:
  beehive-network:
    driver: bridge
